# Generated by Django 6.0.2 on 2026-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SECRETARIA', 'Secretaria'), ('COORDENACAO', 'Coordenador de Curso'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
