# Generated by Django 6.0.3 on 2026-05-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_componentecurricular_conteudo_modulo'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-data_lancamento', 'descricao'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='nota',
            name='componente_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='cursos.componentecurricular', verbose_name='Componente Curricular'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_lancamento',
            field=models.DateField(verbose_name='Data de Lancamento'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='descricao',
            field=models.CharField(max_length=120, verbose_name='Descricao/Avaliacao'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
