# Generated by Django 5.2.5 on 2026-03-26 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtendimentoPedagogico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_atendimento", models.DateField(default=django.utils.timezone.localdate, verbose_name="Data do atendimento")),
                ("diagnostico", models.TextField(verbose_name="Diagnostico")),
                ("plano_acao", models.TextField(verbose_name="Plano de acao")),
                ("status", models.CharField(choices=[("RISCO_REPROVACAO", "Risco de reprovacao"), ("RISCO_EVASAO", "Risco de evasao"), ("PLANO_RECUPERACAO", "Plano de recuperacao"), ("ACOMPANHAMENTO_PSICOPEDAGOGICO", "Acompanhamento psicopedagogico"), ("CONCLUIDO", "Concluido")], default="RISCO_REPROVACAO", max_length=40, verbose_name="Status")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="atendimentos_pedagogicos", to=settings.AUTH_USER_MODEL, verbose_name="Aluno")),
                ("pedagogia_responsavel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="atendimentos_pedagogicos_responsavel", to=settings.AUTH_USER_MODEL, verbose_name="Pedagogia responsavel")),
            ],
            options={
                "verbose_name": "Atendimento pedagogico",
                "verbose_name_plural": "Atendimentos pedagogicos",
                "ordering": ["-data_atendimento", "-id"],
            },
        ),
    ]
