version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: gestao_escolar
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-user-postgresql.sql:/docker-entrypoint-initdb.d/init-user-postgresql.sql
      - /etc/localtime:/etc/localtime:ro
      
volumes:
  db_data:
  postgres_data:
  esdata:
    driver: local
  esdata2:  # Added the missing volume declaration