version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: gestao_escolar
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-user-postgresql.sql:/docker-entrypoint-initdb.d/init-user-postgresql.sql
      - /etc/localtime:/etc/localtime:ro
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_USERNAME: user
      ELASTICSEARCH_PASSWORD: 1234
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    links:
      - es
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.2
    volumes:
      - ./logstash/cars.csv:/cars.csv
      - ./logstash/pipelines/:/usr/share/logstash/pipeline/
      - /etc/localtime:/etc/localtime:ro
    links:
      - es
      
volumes:
  db_data:
  postgres_data:
  esdata:
    driver: local
  esdata2:  # Added the missing volume declaration