# Generated by Django 6.0.3 on 2026-03-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('VISUALIZACAO', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('AVANCO_FLUXO', 'Avanço de Fluxo'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo / Entidade')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Ação')),
                ('dados', models.JSONField(blank=True, null=True, verbose_name='Dados (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data'],
            },
        ),
    ]
