# Generated by Django 6.0.2 on 2026-03-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('TRANCADA', 'Trancada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='ATIVA', max_length=20)),
            ],
        ),
    ]
