# Generated by Django 6.0.3 on 2026-03-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_matricula_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='tipo_matricula',
            field=models.CharField(choices=[('NOVA', 'Nova Matrícula'), ('REMATRICULA', 'Rematrícula')], default='NOVA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PendenciaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Pendência')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_resolucao', models.DateField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Pendência Documental',
                'verbose_name_plural': 'Pendências Documentais',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG / Documento de Identidade'), ('CPF', 'CPF'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('HISTORICO_ESCOLAR', 'Histórico Escolar'), ('FOTO', 'Foto 3x4'), ('CERTIDAO_NASCIMENTO', 'Certidão de Nascimento'), ('DECLARACAO_TRANSFERENCIA', 'Declaração de Transferência'), ('OUTROS', 'Outros')], max_length=40, verbose_name='Tipo de Documento')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Documento da Matrícula',
                'verbose_name_plural': 'Documentos da Matrícula',
                'ordering': ['tipo_documento'],
                'unique_together': {('matricula', 'tipo_documento')},
            },
        ),
    ]
