# Generated by Django 6.0.3 on 2026-03-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_add_transferencia_regra_consolidacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='turno',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], max_length=10, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='pendenciadocumental',
            name='orientacao_aluno',
            field=models.TextField(blank=True, verbose_name='Orientação ao Aluno'),
        ),
        migrations.AddField(
            model_name='pendenciadocumental',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para Resolução'),
        ),
        migrations.AlterField(
            model_name='pendenciadocumental',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação (Interno)'),
        ),
        migrations.CreateModel(
            name='FluxoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_matricula', models.CharField(choices=[('NOVA', 'Nova Matrícula'), ('REMATRICULA', 'Rematrícula')], default='NOVA', max_length=20, verbose_name='Tipo')),
                ('etapa_atual', models.CharField(choices=[('REQUERIMENTO_RECEBIDO', 'Receber Requerimento'), ('DOCUMENTOS_CONFERIDOS', 'Conferir Documentos'), ('PENDENCIA_ABERTA', 'Pendência + Prazo'), ('REQUISITOS_VALIDADOS', 'Validar Requisitos'), ('MATRICULA_REGISTRADA', 'Registrar Matrícula'), ('ALUNO_ENTURMADO', 'Enturmar / Alocar Turno'), ('COMPROVANTE_EMITIDO', 'Emitir Comprovante'), ('ARQUIVADO', 'Arquivar (Classificar + Indexar)')], default='REQUERIMENTO_RECEBIDO', max_length=30, verbose_name='Etapa Atual')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_matricula', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('documento_comprovante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_comprovante', to='matriculas.documentoemitido', verbose_name='Comprovante Emitido')),
                ('matricula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Fluxo de Matrícula',
                'verbose_name_plural': 'Fluxos de Matrícula',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('REQUERIMENTO_RECEBIDO', 'Receber Requerimento'), ('DOCUMENTOS_CONFERIDOS', 'Conferir Documentos'), ('PENDENCIA_ABERTA', 'Pendência + Prazo'), ('REQUISITOS_VALIDADOS', 'Validar Requisitos'), ('MATRICULA_REGISTRADA', 'Registrar Matrícula'), ('ALUNO_ENTURMADO', 'Enturmar / Alocar Turno'), ('COMPROVANTE_EMITIDO', 'Emitir Comprovante'), ('ARQUIVADO', 'Arquivar (Classificar + Indexar)')], max_length=30, verbose_name='Etapa')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_fluxo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_etapas', to='matriculas.fluxomatricula')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo',
                'verbose_name_plural': 'Etapas do Fluxo',
                'ordering': ['data'],
            },
        ),
    ]
