# Generated by Django 6.0.2 on 2026-03-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_add_fluxo_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentomatricula',
            options={'ordering': ['tipo_documento'], 'verbose_name': 'Documento da Matricula', 'verbose_name_plural': 'Documentos da Matricula'},
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='matriculas/documentos/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='data_validacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validacao'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='motivo_recusa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo da Recusa'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('VALIDADO', 'Validado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_matricula_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero_matricula',
            field=models.CharField(blank=True, editable=False, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='tipo_documento',
            field=models.CharField(choices=[('RG', 'RG / Documento de Identidade'), ('CPF', 'CPF'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residencia'), ('HISTORICO_ESCOLAR', 'Historico Escolar'), ('FOTO', 'Foto 3x4'), ('CERTIDAO_NASCIMENTO', 'Certidao de Nascimento'), ('DECLARACAO_TRANSFERENCIA', 'Declaracao de Transferencia'), ('OUTROS', 'Outros')], max_length=40, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='etapafluxoemissao',
            name='etapa',
            field=models.CharField(choices=[('PROTOCOLO_ABERTO', 'Abrir Protocolo'), ('ELEGIBILIDADE_VERIFICADA', 'Verificar Elegibilidade'), ('DOCUMENTO_GERADO', 'Gerar Documento Padrão'), ('DOCUMENTO_VALIDADO', 'Assinar / Validar'), ('ENTREGA_REGISTRADA', 'Registrar Entrega'), ('ARQUIVADO', 'Arquivamento')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='fluxoemissaodocumento',
            name='etapa_atual',
            field=models.CharField(choices=[('PROTOCOLO_ABERTO', 'Abrir Protocolo'), ('ELEGIBILIDADE_VERIFICADA', 'Verificar Elegibilidade'), ('DOCUMENTO_GERADO', 'Gerar Documento Padrão'), ('DOCUMENTO_VALIDADO', 'Assinar / Validar'), ('ENTREGA_REGISTRADA', 'Registrar Entrega'), ('ARQUIVADO', 'Arquivamento')], default='PROTOCOLO_ABERTO', max_length=30, verbose_name='Etapa Atual'),
        ),
        migrations.CreateModel(
            name='TermoAssinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_termo', models.CharField(choices=[('MATRICULA', 'Termo de Matricula'), ('CIENCIA_PENDENCIA', 'Ciencia de Pendencia Documental'), ('LGPD', 'Ciencia de Tratamento de Dados (LGPD)'), ('OUTRO', 'Outro')], max_length=30)),
                ('data_assinatura', models.DateField()),
                ('assinado_por', models.CharField(max_length=200)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='matriculas/termos/')),
                ('observacao', models.TextField(blank=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_assinados', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Termo Assinado',
                'verbose_name_plural': 'Termos Assinados',
                'ordering': ['-data_assinatura', '-id'],
            },
        ),
    ]
