# Generated by Django 6.0.2 on 2026-03-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_aproveitamentocomponente_certificadodiploma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Nº do Documento')),
                ('tipo', models.CharField(choices=[('CONSELHO_CLASSE', 'Conselho de Classe'), ('RESULTADO_FINAL', 'Resultado Final'), ('REUNIAO_PEDAGOGICA', 'Reunião Pedagógica')], default='CONSELHO_CLASSE', max_length=25, verbose_name='Tipo de Ata')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('unidade_nome', models.CharField(max_length=200, verbose_name='Unidade Escolar')),
                ('local_reuniao', models.CharField(max_length=200, verbose_name='Local da Reunião')),
                ('data_reuniao', models.DateField(verbose_name='Data da Reunião')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Encerramento')),
                ('membros_presentes', models.TextField(help_text='Um por linha: Nome – Cargo', verbose_name='Membros Presentes')),
                ('abertura', models.TextField(verbose_name='Texto de Abertura')),
                ('deliberacoes', models.TextField(verbose_name='Deliberações / Decisões')),
                ('encerramento', models.TextField(verbose_name='Texto de Encerramento')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('conselho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata_escolar', to='matriculas.conselhoclasse', verbose_name='Conselho de Classe')),
                ('presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_presididas', to=settings.AUTH_USER_MODEL, verbose_name='Presidente da Reunião')),
                ('secretario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_secretariadas', to=settings.AUTH_USER_MODEL, verbose_name='Secretário(a)')),
            ],
            options={
                'verbose_name': 'Ata Escolar',
                'verbose_name_plural': 'Atas Escolares',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diploma', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Nº do Diploma')),
                ('codigo_verificacao', models.CharField(editable=False, max_length=36, unique=True, verbose_name='Código de Verificação')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo do Aluno')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('local_nascimento', models.CharField(max_length=100, verbose_name='Local de Nascimento')),
                ('nome_pai', models.CharField(blank=True, max_length=200, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=200, verbose_name='Nome da Mãe')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('curso_nome', models.CharField(max_length=200, verbose_name='Curso')),
                ('habilitacao', models.CharField(blank=True, max_length=200, verbose_name='Habilitação')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária Total (h)')),
                ('data_inicio_curso', models.DateField(verbose_name='Data de Início do Curso')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Final')),
                ('unidade_nome', models.CharField(max_length=200, verbose_name='Unidade Escolar')),
                ('municipio_uf', models.CharField(max_length=100, verbose_name='Município/UF')),
                ('diretor_nome', models.CharField(max_length=200, verbose_name='Nome do Diretor(a)')),
                ('diretor_cargo', models.CharField(default='Diretor(a)', max_length=100, verbose_name='Cargo do Diretor(a)')),
                ('secretario_nome', models.CharField(max_length=200, verbose_name='Nome do(a) Secretário(a) Escolar')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_escolar', to='matriculas.certificadodiploma', verbose_name='Certificado / Diploma')),
            ],
            options={
                'verbose_name': 'Diploma Escolar',
                'verbose_name_plural': 'Diplomas Escolares',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
