# Generated by Django 6.0.3 on 2026-03-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ['-data'], 'verbose_name': 'TramitaÃ§Ã£o', 'verbose_name_plural': 'TramitaÃ§Ãµes'},
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de ConclusÃ£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='NÂº do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRAMITACAO', 'Em TramitaÃ§Ã£o'), ('CONCLUIDO', 'ConcluÃ\xaddo'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('REQUERIMENTO', 'Requerimento'), ('RECURSO', 'Recurso'), ('TRANSFERENCIA', 'TransferÃªncia'), ('SOLICITACAO', 'SolicitaÃ§Ã£o Geral'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='acao',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('ENCAMINHADO', 'Encaminhado'), ('RESPONDIDO', 'Respondido'), ('ARQUIVADO', 'Arquivado'), ('DEVOLVIDO', 'Devolvido')], max_length=15, verbose_name='AÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='ResponsÃ¡vel'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATRICULA', 'Matrícula / Rematrícula'), ('TRANSFERENCIA', 'Transferência'), ('DOCUMENTO', 'Emissão de Documento'), ('RECURSO', 'Recurso'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=15, verbose_name='Status')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_resolucao', models.DateField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='processos.processo', verbose_name='Processo Vinculado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
