# Generated by Django 6.0.3 on 2026-03-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0009_add_fluxo_transferencia'),
        ('processos', '0002_alter_tramitacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaOficioMemorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('tipo', models.CharField(choices=[('ATA', 'Ata'), ('OFICIO', 'Ofício'), ('MEMORANDO', 'Memorando')], max_length=10, verbose_name='Tipo')),
                ('destinatario', models.CharField(blank=True, max_length=255, verbose_name='Destinatário')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matriculas.matricula', verbose_name='Matrícula')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_oficios', to='processos.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Ata / Ofício / Memorando',
                'verbose_name_plural': 'Atas / Ofícios / Memorandos',
                'ordering': ['-data_emissao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('tipo', models.CharField(choices=[('MATRICULA', 'Declaração de Matrícula'), ('FREQUENCIA', 'Declaração de Frequência'), ('CONCLUSAO', 'Declaração de Conclusão de Curso')], max_length=15, verbose_name='Tipo de Declaração')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Declaração',
                'verbose_name_plural': 'Declarações',
                'ordering': ['-data_emissao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('escola_origem', models.CharField(blank=True, max_length=200, verbose_name='Escola de Origem')),
                ('escola_destino', models.CharField(blank=True, max_length=200, verbose_name='Escola de Destino')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matriculas.matricula', verbose_name='Matrícula')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='matriculas.transferencia', verbose_name='Transferência')),
            ],
            options={
                'verbose_name': 'Guia de Transferência',
                'verbose_name_plural': 'Guias de Transferência',
                'ordering': ['-data_emissao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('tipo', models.CharField(choices=[('COMPLETO', 'Histórico Completo'), ('PARCIAL', 'Histórico Parcial')], default='COMPLETO', max_length=10, verbose_name='Tipo')),
                ('periodo_ref', models.CharField(blank=True, max_length=50, verbose_name='Período de Referência')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
                'ordering': ['-data_emissao'],
                'abstract': False,
            },
        ),
    ]
