# Generated by Django 6.0.3 on 2026-03-05 16:59

import apps.documentos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='ano',
            field=models.PositiveIntegerField(default=apps.documentos.models._ano_atual, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='assinaturas',
            field=models.JSONField(blank=True, default=list, verbose_name='Assinaturas'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='chave_autenticidade',
            field=models.CharField(blank=True, max_length=32, verbose_name='Chave de Autenticidade'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='cidade_uf',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade/UF'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='data_emissao_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Emissão Final'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='data_reuniao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Reunião'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='deliberacoes',
            field=models.JSONField(blank=True, default=list, verbose_name='Relato e Deliberações'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='encaminhamentos',
            field=models.JSONField(blank=True, default=list, verbose_name='Encaminhamentos'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='folha_pagina',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folha/Página'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='forma_assinatura',
            field=models.CharField(blank=True, max_length=120, verbose_name='Forma de Assinatura'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='horario_encerramento',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Encerramento'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='horario_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='link_reuniao',
            field=models.URLField(blank=True, verbose_name='Link da Reunião'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='livro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='local_reuniao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDA', 'Híbrida')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='numero_ata',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da Ata'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='participantes',
            field=models.JSONField(blank=True, default=list, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='pauta',
            field=models.JSONField(blank=True, default=list, verbose_name='Pauta'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='presidente_reuniao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Presidente/Coordenação'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='responsavel_lavratura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsável pela Lavratura'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='situacao',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido')], default='RASCUNHO', max_length=12, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='texto_abertura',
            field=models.TextField(blank=True, verbose_name='Texto de Abertura'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='texto_final',
            field=models.TextField(blank=True, verbose_name='Texto Final'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='tipo_reuniao_outro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Outro Tipo de Reunião'),
        ),
        migrations.AddField(
            model_name='ataoficiomemorando',
            name='tipo_reuniao_registro',
            field=models.CharField(blank=True, choices=[('CONSELHO_ESCOLAR', 'Conselho Escolar'), ('CONSELHO_CLASSE', 'Conselho de Classe'), ('REUNIAO_PEDAGOGICA', 'Reunião Pedagógica'), ('REUNIAO_ADMINISTRATIVA', 'Reunião Administrativa'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de Reunião/Registro'),
        ),
        migrations.CreateModel(
            name='AtaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anexo', models.CharField(choices=[('LISTA_PRESENCA', 'Lista de presença'), ('RELATORIO', 'Relatório'), ('FOTOS', 'Fotos'), ('PRINTS', 'Prints'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo do Anexo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/atas/anexos/', verbose_name='Arquivo')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_upload', to='documentos.ataoficiomemorando')),
            ],
            options={
                'verbose_name': 'Anexo da Ata',
                'verbose_name_plural': 'Anexos da Ata',
            },
        ),
    ]
