# Generated by Django 6.0.2 on 2026-03-16 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0012_curso_moodle_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleWritebackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsfunction', models.CharField(max_length=100, verbose_name='Função Moodle')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=20, verbose_name='Status')),
                ('moodle_course_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Curso no Moodle')),
                ('moodle_assignment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Atividade no Moodle')),
                ('moodle_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Usuário no Moodle')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload de Requisição')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Payload de Resposta')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Escrita no Moodle',
                'verbose_name_plural': 'Logs de Escrita no Moodle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_category_id', models.PositiveIntegerField(unique=True, verbose_name='ID da Categoria no Moodle')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('idnumber', models.CharField(blank=True, default='', max_length=100, verbose_name='ID Number')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('descricao_formato', models.PositiveSmallIntegerField(default=0, verbose_name='Formato da Descrição')),
                ('sortorder', models.IntegerField(default=0, verbose_name='Ordem')),
                ('coursecount', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Cursos')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='Profundidade')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='Path')),
                ('timemodified', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de Modificação')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='integracao_moodle.moodlecategory', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Moodle',
                'verbose_name_plural': 'Categorias Moodle',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MoodleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_course_id', models.PositiveIntegerField(unique=True, verbose_name='ID do Curso no Moodle')),
                ('shortname', models.CharField(blank=True, default='', max_length=100, verbose_name='Shortname')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('displayname', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome de Exibição')),
                ('idnumber', models.CharField(blank=True, default='', max_length=100, verbose_name='ID Number')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Resumo')),
                ('summaryformat', models.PositiveSmallIntegerField(default=0, verbose_name='Formato do Resumo')),
                ('format', models.CharField(blank=True, default='', max_length=50, verbose_name='Formato')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('startdate', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de Início')),
                ('enddate', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de Fim')),
                ('timecreated', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de Criação')),
                ('timemodified', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de Modificação')),
                ('enablecompletion', models.BooleanField(default=False, verbose_name='Acompanhamento de Conclusão')),
                ('showactivitydates', models.BooleanField(default=False, verbose_name='Exibir Datas de Atividades')),
                ('showcompletionconditions', models.BooleanField(default=False, verbose_name='Exibir Condições de Conclusão')),
                ('courseformatoptions', models.JSONField(blank=True, default=list, verbose_name='Opções de Formato')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='integracao_moodle.moodlecategory', verbose_name='Categoria Moodle')),
                ('curso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_moodle', to='cursos.curso', verbose_name='Curso Interno Vinculado')),
            ],
            options={
                'verbose_name': 'Curso Moodle',
                'verbose_name_plural': 'Cursos Moodle',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='MoodleGradeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('grade_tree', 'Árvore de Notas'), ('gradeitems', 'Itens de Nota'), ('user_grade_items', 'Itens de Nota por Usuário'), ('user_grades_table', 'Tabela de Notas por Usuário')], max_length=40, verbose_name='Tipo do Snapshot')),
                ('wsfunction', models.CharField(max_length=100, verbose_name='Função Moodle')),
                ('moodle_course_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Curso no Moodle')),
                ('moodle_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Usuário no Moodle')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload de Requisição')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Payload de Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_snapshots', to='integracao_moodle.moodlecourse', verbose_name='Curso Moodle')),
            ],
            options={
                'verbose_name': 'Snapshot de Notas do Moodle',
                'verbose_name_plural': 'Snapshots de Notas do Moodle',
                'ordering': ['-created_at'],
            },
        ),
    ]
