# Generated by Django 6.0.2 on 2026-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_moodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', max_length=1024, verbose_name='Moodle Base URL')),
                ('token', models.CharField(blank=True, default='', max_length=255, verbose_name='WS Token')),
                ('rest_format', models.CharField(blank=True, default='json', max_length=50, verbose_name='REST Format')),
                ('rest_path', models.CharField(blank=True, default='/webservice/rest/server.php', max_length=255, verbose_name='REST Path')),
                ('timeout', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (s)')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Verify SSL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Integração com Moodle',
                'verbose_name_plural': 'Configurações da Integração com Moodle',
            },
        ),
    ]
