# Generated by Django 6.0.2 on 2026-03-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
