# Generated by Django 6.0.3 on 2026-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_status'),
        ('turmas', '0004_diarioacademico_componente_curricular'),
    ]

    operations = [
    ]
