# Generated by Django 6.0.2 on 2026-03-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SECRETARIA', 'Secretaria'), ('COORDENACAO', 'Coordenacao/Consulta'), ('ADMIN', 'Administrador')], max_length=20),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(max_length=120)),
                ('municipio', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('principal', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='usuarios.pessoa')),
            ],
            options={
                'ordering': ['-principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ingresso', models.DateField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='usuarios.pessoa')),
            ],
            options={
                'ordering': ['pessoa__nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.pessoa'),
        ),
        migrations.CreateModel(
            name='DocumentoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CERTIDAO', 'Certidao'), ('OUTRO', 'Outro')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('orgao_emissor', models.CharField(blank=True, max_length=50)),
                ('uf_emissor', models.CharField(blank=True, max_length=2)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_pessoais', to='usuarios.pessoa')),
            ],
            options={
                'ordering': ['tipo', 'numero'],
                'unique_together': {('pessoa', 'tipo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('responsavel_principal', models.BooleanField(default=False)),
                ('contato_principal', models.CharField(max_length=120)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='usuarios.aluno')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades', to='usuarios.pessoa')),
            ],
            options={
                'unique_together': {('aluno', 'pessoa', 'parentesco')},
            },
        ),
    ]
