# Generated by Django 6.0.2 on 2026-03-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pessoa_alter_usuario_tipo_endereco_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
    ]
