# Generated by Django 6.0.3 on 2026-03-27 13:34

import apps.certificados.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0019_ofertacurso_template_sync_metadata'),
        ('matriculas', '0012_merge_20260305_1203'),
        ('turmas', '0006_diariomaterialaula_diarioocorrencia'),
        ('unidades', '0003_merge_20260305_1203'),
        ('usuarios', '0008_alter_usuario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.CharField(editable=False, max_length=40, unique=True)),
                ('livro', models.CharField(blank=True, default='', max_length=20)),
                ('folha', models.CharField(blank=True, default='', max_length=20)),
                ('termo', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_validacao', models.CharField(editable=False, max_length=40, unique=True)),
                ('qr_code_validacao', models.URLField(blank=True, default='', max_length=800)),
                ('qr_code_data_uri', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DIPLOMA_EM_PREPARACAO', 'diploma em preparação'), ('DIPLOMA_REGISTRADO', 'diploma registrado'), ('DIPLOMA_DISPONIVEL_RETIRADA', 'diploma disponível para retirada'), ('DIPLOMA_ENTREGUE', 'diploma entregue'), ('CERTIFICADO_CANCELADO', 'certificado cancelado')], default='DIPLOMA_EM_PREPARACAO', max_length=40)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('nome_aluno_snapshot', models.CharField(blank=True, default='', max_length=220)),
                ('cpf_aluno_snapshot', models.CharField(blank=True, default='', max_length=14)),
                ('curso_nome_snapshot', models.CharField(blank=True, default='', max_length=220)),
                ('texto_certificado_snapshot', models.TextField(blank=True, default='')),
                ('dados_dinamicos', models.JSONField(blank=True, default=dict)),
                ('reimpressoes', models.PositiveIntegerField(default=0)),
                ('ultima_reimpressao_em', models.DateTimeField(blank=True, null=True)),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='certificados/pdfs/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='usuarios.aluno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='cursos.curso')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos_v2', to='matriculas.matricula')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='turmas.turma')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='unidades.unidade')),
                ('usuario_emissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos_institucionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado Emitido',
                'verbose_name_plural': 'Certificados Emitidos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=190, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('CERTIFICADO_CONCLUSAO', 'Certificado de Conclusão')], default='CERTIFICADO', max_length=30)),
                ('template_html', models.TextField(blank=True, default='')),
                ('stylesheet_css', models.TextField(blank=True, default='')),
                ('texto_certificado', models.TextField(default='O(a) [nome_da_instituicao] certifica que [nome_aluno], portador(a) do CPF [cpf_aluno], concluiu com êxito o curso [curso_nome], pertencente ao eixo tecnológico [eixo_tecnologico], com carga horária total de [carga_horaria] horas, realizado no período de [data_inicio] a [data_fim], com conclusão em [data_conclusao].')),
                ('campos_dinamicos', models.JSONField(default=apps.certificados.models.campos_dinamicos_padrao)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_certificado_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_certificado_criados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_certificado', to='cursos.curso')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_certificado', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Modelo de Certificado',
                'verbose_name_plural': 'Modelos de Certificado',
                'ordering': ['-atualizado_em', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmissaoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('EMISSAO', 'Emissão'), ('EMISSAO_LOTE', 'Emissão em lote'), ('PREVIEW', 'Pré-visualização'), ('GERACAO_PDF', 'Geração de PDF'), ('REIMPRESSAO', 'Reimpressão'), ('VALIDACAO_PUBLICA', 'Validação pública'), ('ALTERACAO_MODELO', 'Alteração de modelo'), ('ALTERACAO_STATUS', 'Alteração de status')], max_length=30)),
                ('descricao', models.TextField(blank=True, default='')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_emissao', to='certificados.certificadoemitido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_emissao_certificados', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_emissao', to='certificados.modelocertificado')),
            ],
            options={
                'verbose_name': 'Histórico de Emissão de Certificado',
                'verbose_name_plural': 'Históricos de Emissão de Certificados',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoVisualCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_instituicao', models.CharField(default='Instituto Estadual de Desenvolvimento da Educação Profissional de Rondônia', max_length=220)),
                ('sigla_instituicao', models.CharField(default='IDEP', max_length=20)),
                ('brasao_instituicao', models.URLField(blank=True, default='')),
                ('logo_instituicao', models.URLField(blank=True, default='')),
                ('logos_rodape', models.JSONField(blank=True, default=list)),
                ('marca_dagua', models.URLField(blank=True, default='')),
                ('cidade_padrao', models.CharField(default='Porto Velho', max_length=120)),
                ('estado_padrao', models.CharField(default='RO', max_length=2)),
                ('cor_primaria', models.CharField(default='#0b2f4b', max_length=20)),
                ('cor_secundaria', models.CharField(default='#0f6c3d', max_length=20)),
                ('cor_destaque', models.CharField(default='#f1c40f', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_visual', to='certificados.modelocertificado')),
            ],
            options={
                'verbose_name': 'Configuração Visual de Certificado',
                'verbose_name_plural': 'Configurações Visuais de Certificados',
            },
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to='certificados.modelocertificado'),
        ),
        migrations.CreateModel(
            name='AssinaturaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=140)),
                ('imagem_assinatura', models.ImageField(blank=True, null=True, upload_to='certificados/assinaturas/')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='certificados.modelocertificado')),
            ],
            options={
                'verbose_name': 'Assinatura de Certificado',
                'verbose_name_plural': 'Assinaturas de Certificados',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
