# Generated by Django 6.0.3 on 2026-03-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
        ('cursos', '0019_ofertacurso_template_sync_metadata'),
        ('matriculas', '0013_dependenciaacademica'),
        ('turmas', '0006_diariomaterialaula_diarioocorrencia'),
        ('unidades', '0003_merge_20260305_1203'),
        ('usuarios', '0008_alter_usuario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaovisualcertificado',
            options={'verbose_name': 'Configuracao Visual de Certificado', 'verbose_name_plural': 'Configuracoes Visuais de Certificados'},
        ),
        migrations.AlterModelOptions(
            name='historicoemissaocertificado',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Historico de Emissao de Certificado', 'verbose_name_plural': 'Historicos de Emissao de Certificados'},
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='hash_integridade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='numero_registro',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='pagina',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/qrcodes/'),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='reemitido_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemissoes', to='certificados.certificadoemitido'),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='status_documento',
            field=models.CharField(choices=[('RASCUNHO', 'rascunho'), ('EMITIDO', 'emitido'), ('CANCELADO', 'cancelado'), ('REEMITIDO', 'reemitido')], default='RASCUNHO', max_length=20),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='tipo_documento',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma'), ('HISTORICO', 'Historico Escolar')], default='DIPLOMA', max_length=20),
        ),
        migrations.AddField(
            model_name='certificadoemitido',
            name='url_validacao',
            field=models.URLField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='certificadoemitido',
            name='status',
            field=models.CharField(choices=[('DIPLOMA_EM_PREPARACAO', 'diploma em preparacao'), ('DIPLOMA_REGISTRADO', 'diploma registrado'), ('DIPLOMA_DISPONIVEL_RETIRADA', 'diploma disponivel para retirada'), ('DIPLOMA_ENTREGUE', 'diploma entregue'), ('CERTIFICADO_CANCELADO', 'certificado cancelado')], default='DIPLOMA_EM_PREPARACAO', max_length=40),
        ),
        migrations.AlterField(
            model_name='configuracaovisualcertificado',
            name='nome_da_instituicao',
            field=models.CharField(default='Instituto Estadual de Desenvolvimento da Educacao Profissional de Rondonia', max_length=220),
        ),
        migrations.AlterField(
            model_name='historicoemissaocertificado',
            name='acao',
            field=models.CharField(choices=[('EMISSAO', 'Emissao'), ('EMISSAO_LOTE', 'Emissao em lote'), ('REEMISSAO', 'Reemissao'), ('PREVIEW', 'Pre-visualizacao'), ('GERACAO_PDF', 'Geracao de PDF'), ('REIMPRESSAO', 'Reimpressao'), ('CANCELAMENTO', 'Cancelamento'), ('VALIDACAO_PUBLICA', 'Validacao publica'), ('VALIDACAO_STATUS', 'Consulta de status de validacao'), ('ALTERACAO_MODELO', 'Alteracao de modelo'), ('ALTERACAO_STATUS', 'Alteracao de status')], max_length=30),
        ),
        migrations.AlterField(
            model_name='modelocertificado',
            name='texto_certificado',
            field=models.TextField(default='O(a) [nome_da_instituicao] certifica que [nome_aluno], portador(a) do CPF [cpf_aluno], concluiu com exito o curso [curso_nome], pertencente ao eixo tecnologico [eixo_tecnologico], com carga horaria total de [carga_horaria] horas, realizado no periodo de [data_inicio] a [data_fim], com conclusao em [data_conclusao].'),
        ),
        migrations.AlterField(
            model_name='modelocertificado',
            name='tipo',
            field=models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('CERTIFICADO_CONCLUSAO', 'Certificado de Conclusao')], default='CERTIFICADO', max_length=30),
        ),
        migrations.AddIndex(
            model_name='certificadoemitido',
            index=models.Index(fields=['tipo_documento', 'status_documento'], name='certificado_tipo_do_46ca37_idx'),
        ),
        migrations.AddIndex(
            model_name='certificadoemitido',
            index=models.Index(fields=['numero_registro'], name='certificado_numero__fb6126_idx'),
        ),
        migrations.AddIndex(
            model_name='certificadoemitido',
            index=models.Index(fields=['livro', 'folha', 'pagina'], name='certificado_livro_38f9e9_idx'),
        ),
    ]
