# Generated by Django 6.0.3 on 2026-03-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº do Processo')),
                ('tipo', models.CharField(choices=[('REQUERIMENTO', 'Requerimento'), ('RECURSO', 'Recurso'), ('TRANSFERENCIA', 'Transferência'), ('SOLICITACAO', 'Solicitação Geral'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRAMITACAO', 'Em Tramitação'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('requerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_requeridos', to=settings.AUTH_USER_MODEL, verbose_name='Requerente')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_destino', models.CharField(blank=True, max_length=100, verbose_name='Setor de Destino')),
                ('acao', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('ENCAMINHADO', 'Encaminhado'), ('RESPONDIDO', 'Respondido'), ('ARQUIVADO', 'Arquivado'), ('DEVOLVIDO', 'Devolvido')], max_length=15, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='processos.processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tramitação',
                'verbose_name_plural': 'Tramitações',
                'ordering': ['-data'],
            },
        ),
    ]
