# Generated by Django 6.0.3 on 2026-03-27 12:00

from django.db import migrations, models


def seed_hipoteses_legais(apps, schema_editor):
    HipoteseLegal = apps.get_model("processos", "HipoteseLegal")
    hipoteses = [
        ("Auditoria Interna", "Art. 15, 40, da Lei no 9.960/2001", "RESTRITO"),
        ("Auditoria Interna - Controle Interno", "Art. 26, 3o, da Lei no 10.180/2001", "SIGILOSO"),
        ("Comunicacao de Irregularidades", "Art. 16, 2o da IN 05/2018 da OGU", "SIGILOSO"),
        ("Controle Interno", "Art. 26, 3o, da Lei no 10.180/2001", "RESTRITO"),
        ("Correcao: Investigacao de Responsabilidade", "Art. 150 da Lei no 8.112/1990", "SIGILOSO"),
        ("Direito Autoral", "Art. 24, III, da Lei no 9.610/1998", "RESTRITO"),
        ("Documento Preparatorio", "Art. 7o, 3o, da Lei no 12.527/2011", "RESTRITO"),
        ("Documento Severamente Restrito", "Lei 123789/2020", "RESTRITO"),
        ("Informacao Pessoal", "Art. 31 da Lei no 12.527/2011", "RESTRITO"),
        ("Informacao Restrita", "Informacao Restrita", "RESTRITO"),
        ("Informacoes Privilegiadas de Sociedades Anonimas", "Art. 155, 2o, da Lei no 6.404/1976", "RESTRITO"),
        ("Interceptacao de Comunicacoes Telefonicas", "Art. 8o, caput, da Lei no 9.296/1996", "RESTRITO"),
        ("Investigacao de Responsabilidade de Servidor", "Lei no 8.112/1990", "RESTRITO"),
        ("Licenciamento Ambiental", "Lei no 6.938/1981", "PUBLICO"),
        ("Pesquisa Cientifica Sensivel", "Lei no 10.973/2004", "SIGILOSO"),
        ("Dados Bancarios", "Lei Complementar no 105/2001", "SIGILOSO"),
        ("Dados Fiscais", "Art. 198 do CTN", "SIGILOSO"),
        ("Protecao de Dados Pessoais", "Lei no 13.709/2018", "RESTRITO"),
        ("Seguranca Institucional", "Lei no 12.527/2011", "RESTRITO"),
        ("Relatorio de Inteligencia", "Decreto no 9.690/2019", "SIGILOSO"),
        ("Relatorio Tecnico Preliminar", "Lei no 14.133/2021", "RESTRITO"),
        ("Parecer Juridico Interno", "Lei Complementar no 73/1993", "RESTRITO"),
        ("Ato de Designacao Sigiloso", "Lei no 8.159/1991", "SIGILOSO"),
        ("Processo Administrativo Reservado", "Lei no 9.784/1999", "RESTRITO"),
        ("Planejamento Estrategico Interno", "Norma interna institucional", "RESTRITO"),
    ]

    objetos = [
        HipoteseLegal(descricao=descricao, base_legal=base_legal, nivel_acesso=nivel_acesso)
        for descricao, base_legal, nivel_acesso in hipoteses
    ]
    HipoteseLegal.objects.bulk_create(objetos, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0002_alter_tramitacao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HipoteseLegal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=255, unique=True, verbose_name="Descricao")),
                ("base_legal", models.CharField(max_length=255, verbose_name="Base legal")),
                (
                    "nivel_acesso",
                    models.CharField(
                        choices=[("PUBLICO", "Publico"), ("RESTRITO", "Restrito"), ("SIGILOSO", "Sigiloso")],
                        default="RESTRITO",
                        max_length=20,
                        verbose_name="Nivel de acesso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("data_criacao", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("data_atualizacao", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Hipotese Legal",
                "verbose_name_plural": "Hipoteses Legais",
                "ordering": ["descricao", "id"],
            },
        ),
        migrations.RunPython(seed_hipoteses_legais, migrations.RunPython.noop),
    ]
