# Generated by Django 6.0.2 on 2026-03-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(blank=True, default='', max_length=30)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('setor_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsetores', to='setores.setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome', 'codigo'],
            },
        ),
    ]
