# Generated by Django 6.0.2 on 2026-03-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.CharField(max_length=9, verbose_name='Ano Letivo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('dias_letivos', models.PositiveIntegerField(default=200, verbose_name='Dias Letivos')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('VIGENTE', 'Vigente'), ('ENCERRADO', 'Encerrado')], default='PLANEJADO', max_length=10, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Calendário Letivo',
                'verbose_name_plural': 'Calendários Letivos',
                'ordering': ['-ano_letivo', 'curso'],
                'unique_together': {('ano_letivo', 'curso')},
            },
        ),
    ]
