# Generated by Django 6.0.2 on 2026-03-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_calendarioletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='eixo_tecnologico',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Eixo Tecnológico'),
        ),
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horária (h)')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('curso', 'nome')},
            },
        ),
    ]
