# Generated by Django 6.0.3 on 2026-05-06 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0020_componentecurricular_conteudo_modulo'),
        ('matriculas', '0016_documentoobrigatoriocurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('INADIMPLENTE', 'Inadimplente'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original (sem descontos)')),
                ('quantidade_parcelas', models.PositiveIntegerField(verbose_name='Quantidade de Parcelas')),
                ('tipo_bolsa', models.CharField(choices=[('SEM_BOLSA', 'Sem Bolsa'), ('SOCIAL', 'Bolsa Social'), ('MERITO', 'Bolsa Merito'), ('FUNCIONARIO', 'Bolsa Funcionario'), ('CONVENIO', 'Bolsa Convenio'), ('OUTRA', 'Outra')], default='SEM_BOLSA', max_length=15, verbose_name='Tipo de Bolsa')),
                ('percentual_bolsa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Bolsa (%)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_financeiro', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Contrato Financeiro',
                'verbose_name_plural': 'Contratos Financeiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criacao do Contrato'), ('PAGAMENTO', 'Pagamento'), ('CANCELAMENTO', 'Cancelamento'), ('REEMISSAO_BOLETO', 'Reemissao de Boleto'), ('ALTERACAO_BOLSA', 'Alteracao de Bolsa'), ('NEGATIVACAO', 'Negativacao'), ('ACORDO', 'Acordo')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='financeiro.contratofinanceiro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_financeiros', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historico Financeiro',
                'verbose_name_plural': 'Historicos Financeiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('quantidade_parcelas', models.PositiveIntegerField(default=12, verbose_name='Quantidade de Parcelas')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICA', 'Parcela Unica')], default='MENSAL', max_length=15, verbose_name='Periodicidade')),
                ('permite_bolsa', models.BooleanField(default=True, verbose_name='Permite Bolsa')),
                ('percentual_bolsa_maximo', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Percentual Maximo de Bolsa (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_pagamento', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Plano de Pagamento',
                'verbose_name_plural': 'Planos de Pagamento',
                'ordering': ['curso__nome'],
            },
        ),
        migrations.AddField(
            model_name='contratofinanceiro',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='financeiro.planopagamento'),
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Numero da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada'), ('ISENTA', 'Isenta')], default='PENDENTE', max_length=12, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('numero_boleto', models.CharField(blank=True, max_length=50, verbose_name='Numero do Boleto')),
                ('linha_digitavel', models.CharField(blank=True, max_length=60, verbose_name='Linha Digitavel')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contratofinanceiro')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['contrato', 'numero_parcela'],
                'unique_together': {('contrato', 'numero_parcela')},
            },
        ),
    ]
