# Generated by Django 6.0.2 on 2026-03-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0010_aproveitamentocomponente_certificadodiploma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa / Instituição')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('responsavel_empresa', models.CharField(blank=True, max_length=200, verbose_name='Responsável na Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, verbose_name='E-mail da Empresa')),
                ('telefone_empresa', models.CharField(blank=True, max_length=20, verbose_name='Telefone da Empresa')),
                ('numero_convenio', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Nº do Convênio')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=15, verbose_name='Status')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto do Convênio')),
                ('responsavel_idep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convenios_estagio', to=settings.AUTH_USER_MODEL, verbose_name='Responsável IDEP')),
            ],
            options={
                'verbose_name': 'Convênio de Estágio',
                'verbose_name_plural': 'Convênios de Estágio',
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('OBRIGATORIO', 'Obrigatório'), ('NAO_OBRIGATORIO', 'Não Obrigatório')], default='OBRIGATORIO', max_length=20, verbose_name='Modalidade')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa / Local de Estágio')),
                ('supervisor_empresa', models.CharField(blank=True, max_length=200, verbose_name='Supervisor na Empresa')),
                ('carga_horaria_total', models.PositiveIntegerField(default=0, verbose_name='Carga Horária Total (h)')),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=0, verbose_name='Carga Horária Semanal (h)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim_prevista', models.DateField(blank=True, null=True, verbose_name='Data Fim Prevista')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Data Fim Real')),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('INTERROMPIDO', 'Interrompido')], default='PREVISTO', max_length=15, verbose_name='Status')),
                ('bolsa_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bolsa Mensal (R$)')),
                ('seguro_numero', models.CharField(blank=True, max_length=50, verbose_name='Nº Apólice do Seguro')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios', to='estagio.convenio', verbose_name='Convênio')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='matriculas.matricula', verbose_name='Matrícula')),
                ('orientador_idep', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_orientados', to=settings.AUTH_USER_MODEL, verbose_name='Orientador IDEP')),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISITA', 'Visita ao Local'), ('RELATORIO', 'Relatório do Estagiário'), ('AVALIACAO', 'Avaliação pelo Supervisor'), ('ORIENTACAO', 'Orientação pelo IDEP')], max_length=15, verbose_name='Tipo de Acompanhamento')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição / Observações')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_estagio', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='estagio.estagio', verbose_name='Estágio')),
            ],
            options={
                'verbose_name': 'Acompanhamento de Estágio',
                'verbose_name_plural': 'Acompanhamentos de Estágio',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TermoCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_termo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº do Termo')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Assinatura'), ('ASSINADO', 'Assinado'), ('ADITADO', 'Aditado'), ('ENCERRADO', 'Encerrado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('assinado_aluno', models.BooleanField(default=False, verbose_name='Assinado pelo Aluno')),
                ('assinado_empresa', models.BooleanField(default=False, verbose_name='Assinado pela Empresa')),
                ('assinado_idep', models.BooleanField(default=False, verbose_name='Assinado pelo IDEP')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='estagio.estagio', verbose_name='Estágio')),
            ],
            options={
                'verbose_name': 'Termo de Compromisso',
                'verbose_name_plural': 'Termos de Compromisso',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
