# Generated by Django 6.0.2 on 2026-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=12),
        ),
    ]
