# Generated by Django 6.0.2 on 2026-03-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período (ex: 2025/1)')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('REVISAO', 'Em Revisão')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Diário Acadêmico',
                'verbose_name_plural': 'Diários Acadêmicos',
                'ordering': ['-data_abertura'],
                'unique_together': {('turma', 'periodo')},
            },
        ),
    ]
