# Generated by Django 6.0.2 on 2026-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_diarioacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioacademico',
            name='componente_curricular',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Componente Curricular'),
        ),
    ]
