# Generated by Django 6.0.2 on 2026-03-16 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_merge_20260305_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioMaterialAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('url_material', models.URLField(blank=True, default='', verbose_name='URL do material')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_materiais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_aula', to='turmas.diarioacademico')),
            ],
            options={
                'verbose_name': 'Material de Aula do Diário',
                'verbose_name_plural': 'Materiais de Aula dos Diários',
                'ordering': ['-data_referencia', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiarioOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OCORRENCIA', 'Ocorrência'), ('SUSPENSAO', 'Suspensão')], default='OCORRENCIA', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da ocorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='turmas.diarioacademico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_ocorrencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ocorrência do Diário',
                'verbose_name_plural': 'Ocorrências dos Diários',
                'ordering': ['-data_ocorrencia', '-created_at'],
            },
        ),
    ]
