# Generated by Django 6.0.3 on 2026-03-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_add_tipo_matricula_documentos_pendencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DECLARACAO_MATRICULA', 'Declaração de Matrícula'), ('DECLARACAO_FREQUENCIA', 'Declaração de Frequência'), ('DECLARACAO_CONCLUSAO', 'Declaração de Conclusão de Curso'), ('HISTORICO_ESCOLAR', 'Histórico Escolar'), ('GUIA_TRANSFERENCIA', 'Guia de Transferência')], max_length=30, verbose_name='Tipo de Documento')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('data_validacao', models.DateField(blank=True, null=True, verbose_name='Data de Validação')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('recebido_por', models.CharField(blank=True, max_length=200, verbose_name='Recebido por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_emitidos', to='matriculas.matricula')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Documento Emitido',
                'verbose_name_plural': 'Documentos Emitidos',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
