# Generated by Django 6.0.3 on 2026-03-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('matriculas', '0005_add_documento_emitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Final')),
                ('percentual_frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frequência (%)')),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO_NOTA', 'Reprovado por Nota'), ('REPROVADO_FREQUENCIA', 'Reprovado por Frequência'), ('REPROVADO_AMBOS', 'Reprovado por Nota e Frequência'), ('EM_RECUPERACAO', 'Em Recuperação')], default='PENDENTE', max_length=25, verbose_name='Situação')),
                ('data_consolidacao', models.DateField(blank=True, null=True, verbose_name='Data da Consolidação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidacao', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Consolidação Acadêmica',
                'verbose_name_plural': 'Consolidações Acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='RegraAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_minima', models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Média Mínima')),
                ('frequencia_minima', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Frequência Mínima (%)')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_academica', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Regra Acadêmica',
                'verbose_name_plural': 'Regras Acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('escola_origem', models.CharField(blank=True, max_length=200, verbose_name='Escola de Origem')),
                ('escola_destino', models.CharField(blank=True, max_length=200, verbose_name='Escola de Destino')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_transferencia', models.DateField(blank=True, null=True, verbose_name='Data da Transferência')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROVADA', 'Aprovada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=15, verbose_name='Status')),
                ('numero_guia', models.CharField(blank=True, max_length=20, verbose_name='Nº da Guia')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
