# Generated by Django 6.0.3 on 2026-03-04 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_add_turno_prazo_fluxo_matricula'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEmissaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DECLARACAO_MATRICULA', 'Declaração de Matrícula'), ('DECLARACAO_FREQUENCIA', 'Declaração de Frequência'), ('DECLARACAO_CONCLUSAO', 'Declaração de Conclusão de Curso'), ('HISTORICO_ESCOLAR', 'Histórico Escolar'), ('GUIA_TRANSFERENCIA', 'Guia de Transferência')], max_length=30, verbose_name='Tipo de Documento')),
                ('etapa_atual', models.CharField(choices=[('PROTOCOLO_ABERTO', 'Abrir Protocolo'), ('ELEGIBILIDADE_VERIFICADA', 'Verificar Elegibilidade'), ('DOCUMENTO_GERADO', 'Gerar Documento Padrão'), ('DOCUMENTO_VALIDADO', 'Assinar / Validar'), ('ENTREGA_REGISTRADA', 'Registrar Entrega'), ('ARQUIVADO', 'Arquivar via Protocolo')], default='PROTOCOLO_ABERTO', max_length=30, verbose_name='Etapa Atual')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('elegivel', models.BooleanField(blank=True, null=True, verbose_name='Elegível')),
                ('motivo_inelegivel', models.CharField(blank=True, max_length=255, verbose_name='Motivo de Inelegibilidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('documento_emitido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_emissao', to='matriculas.documentoemitido', verbose_name='Documento Emitido')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_emissao', to='matriculas.matricula', verbose_name='Matrícula')),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_emissao', to='processos.processo', verbose_name='Protocolo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_emissao', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Fluxo de Emissão de Documento',
                'verbose_name_plural': 'Fluxos de Emissão de Documentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxoEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('PROTOCOLO_ABERTO', 'Abrir Protocolo'), ('ELEGIBILIDADE_VERIFICADA', 'Verificar Elegibilidade'), ('DOCUMENTO_GERADO', 'Gerar Documento Padrão'), ('DOCUMENTO_VALIDADO', 'Assinar / Validar'), ('ENTREGA_REGISTRADA', 'Registrar Entrega'), ('ARQUIVADO', 'Arquivar via Protocolo')], max_length=30, verbose_name='Etapa')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_fluxo_emissao', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_etapas', to='matriculas.fluxoemissaodocumento')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo de Emissão',
                'verbose_name_plural': 'Etapas do Fluxo de Emissão',
                'ordering': ['data'],
            },
        ),
    ]
