# Generated by Django 6.0.3 on 2026-03-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_add_fluxo_emissao_documento'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_atual', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('CONFERENCIA_DADOS', 'Conferência de Dados'), ('GUIA_EMITIDA', 'Emitir Guia / Histórico Parcial'), ('BAIXA_ATUALIZADA', 'Baixa / Atualização no Sistema'), ('ARQUIVADO', 'Arquivamento')], default='SOLICITACAO', max_length=20, verbose_name='Etapa Atual')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('documento_emitido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_transferencia', to='matriculas.documentoemitido', verbose_name='Documento Emitido')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_transferencia', to='matriculas.matricula', verbose_name='Matrícula')),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_transferencia', to='processos.processo', verbose_name='Protocolo')),
                ('transferencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo', to='matriculas.transferencia', verbose_name='Transferência')),
            ],
            options={
                'verbose_name': 'Fluxo de Transferência',
                'verbose_name_plural': 'Fluxos de Transferência',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('CONFERENCIA_DADOS', 'Conferência de Dados'), ('GUIA_EMITIDA', 'Emitir Guia / Histórico Parcial'), ('BAIXA_ATUALIZADA', 'Baixa / Atualização no Sistema'), ('ARQUIVADO', 'Arquivamento')], max_length=20, verbose_name='Etapa')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_fluxo_transferencia', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_etapas', to='matriculas.fluxotransferencia')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo de Transferência',
                'verbose_name_plural': 'Etapas do Fluxo de Transferência',
                'ordering': ['data'],
            },
        ),
    ]
