# Generated by Django 6.0.2 on 2026-03-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_add_fluxo_transferencia'),
        ('turmas', '0003_diarioacademico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AproveitamentoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_origem', models.CharField(max_length=255, verbose_name='Componente de Origem')),
                ('instituicao_origem', models.CharField(blank=True, max_length=255, verbose_name='Instituição de Origem')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (h)')),
                ('componente_destino', models.CharField(max_length=255, verbose_name='Componente Equivalente no Curso')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROVADO', 'Aprovado'), ('INDEFERIDO', 'Indeferido')], default='SOLICITADO', max_length=15, verbose_name='Status')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_decisao', models.DateField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa / Observação')),
                ('decisao_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aproveitamentos_decididos', to=settings.AUTH_USER_MODEL, verbose_name='Decisão por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aproveitamentos', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Aproveitamento de Componente',
                'verbose_name_plural': 'Aproveitamentos de Componentes',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma')], default='CERTIFICADO', max_length=15, verbose_name='Tipo')),
                ('numero_registro', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Registro')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDO', 'Emitido'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Certificado / Diploma',
                'verbose_name_plural': 'Certificados / Diplomas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período de Referência')),
                ('data_reuniao', models.DateField(verbose_name='Data da Reunião')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=15, verbose_name='Status')),
                ('pauta', models.TextField(blank=True, verbose_name='Pauta')),
                ('ata', models.TextField(blank=True, verbose_name='Ata da Reunião')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselhos_presididos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conselhos', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Conselho de Classe',
                'verbose_name_plural': 'Conselhos de Classe',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='AtaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Ata')),
                ('numero_ata', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº da Ata')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('conselho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata_resultado', to='matriculas.conselhoclasse', verbose_name='Conselho de Classe')),
            ],
            options={
                'verbose_name': 'Ata de Resultado',
                'verbose_name_plural': 'Atas de Resultado',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
