# Generated by Django 6.0.3 on 2026-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_alter_documentomatricula_options_and_more'),
        ('matriculas', '0011_ataescolar_diplomaescolar'),
    ]

    operations = [
    ]
