# Generated by Django 6.0.2 on 2026-03-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_merge_20260305_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=255, verbose_name='Componente/Disciplina')),
                ('periodo_referencia', models.CharField(blank=True, max_length=50, verbose_name='Período de Referência')),
                ('motivo', models.CharField(choices=[('NOTA', 'Nota'), ('FREQUENCIA', 'Frequência'), ('AMBOS', 'Nota e Frequência'), ('OUTRO', 'Outro')], default='NOTA', max_length=15, verbose_name='Motivo')),
                ('nota_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Obtida')),
                ('frequencia_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frequência (%)')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CUMPRIDA', 'Cumprida'), ('DISPENSADA', 'Dispensada')], default='ATIVA', max_length=15, verbose_name='Status')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_resolucao', models.DateField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='matriculas.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Dependência Acadêmica',
                'verbose_name_plural': 'Dependências Acadêmicas',
                'ordering': ['-data_registro', '-id'],
            },
        ),
    ]
