import {
  Bell,
  LayoutDashboard,
  Rocket,
  FileText,
  Settings,
  GraduationCap,
  Users,
  Power,
} from 'lucide-react'

function unavailable(slug, label, extra = {}) {
  return {
    id: slug,
    type: 'link',
    enabled: false,
    to: `/indisponivel/${slug}`,
    label,
    activePrefixes: [`/indisponivel/${slug}`],
    state: {
      title: label,
      status: extra.status || 'indisponivel',
      description: extra.description || 'Este item do SUAP ainda nao foi integrado ao frontend React.',
    },
  }
}

function activation(slug, label) {
  return unavailable(slug, label, {
    status: 'ativacao',
    description: 'Este modulo aparece no menu legado, mas ainda esta em fase de ativacao no frontend do SUAP.',
  })
}

function rhUnavailable(slug, label, extra = {}) {
  return {
    id: `rh-${slug}`,
    type: 'link',
    enabled: false,
    to: `/rh/${slug}`,
    label,
    activePrefixes: [`/rh/${slug}`],
    state: {
      title: label,
      status: extra.status || 'indisponivel',
      description: extra.description || 'Esta funcionalidade de Gestao de Pessoas ainda nao foi implementada no frontend.',
    },
  }
}

export const sidebarItems = [
  {
    id: 'inicio',
    type: 'link',
    label: 'Início',
    icon: LayoutDashboard,
    to: '/dashboard',
    exact: true,
  },
  {
    id: 'acesso-rapido',
    type: 'group',
    label: 'Acesso Rápido',
    icon: Rocket,
    items: [
      { id: 'cursos', type: 'link', label: 'Cursos', to: '/ensino/cursoinicial/' },
      { id: 'turmas', type: 'link', label: 'Turmas', to: '/turmas' },
      { id: 'matriculas', type: 'link', label: 'Matrículas', to: '/matriculas' },
      { id: 'notas', type: 'link', label: 'Notas', to: '/notas' },
      { id: 'frequencia', type: 'link', label: 'Frequência', to: '/frequencia' },
      { id: 'agenda', type: 'link', label: 'Agenda', to: '/agenda' },
      unavailable('diario-classe', 'Diário de Classe'),
      { id: 'ata-professores', type: 'link', label: 'Ata dos Professores', to: '/ata-professores' },
    ],
  },
  {
    id: 'documentos-processos',
    type: 'group',
    label: 'Documentos e Processos',
    icon: FileText,
    items: [
      {
        id: 'documentos-eletronicos',
        type: 'group',
        label: 'Documentos Eletrônicos',
        items: [
          unavailable('documentos-eletronicos-dashboard', 'Dashboard'),
          { id: 'documentos', type: 'link', label: 'Documentos', to: '/documentos' },
          unavailable('documentos-pessoais', 'Documentos Pessoais'),
          unavailable('documentos-pessoais-digitalizados', 'Documentos Pessoais Digitalizados'),
          {
            id: 'documentos-eletronicos-cadastros',
            type: 'group',
            label: 'Cadastros',
            items: [
              unavailable('documentos-eletronicos-classificacoes', 'Classificações'),
              {
                id: 'documentos-eletronicos-hipoteses-legais',
                type: 'link',
                label: 'Hipóteses Legais',
                to: '/documentos/hipoteses-legais',
                activePrefixes: ['/documentos/hipoteses-legais'],
              },
              unavailable('documentos-eletronicos-modelos', 'Modelos'),
              unavailable('documentos-eletronicos-tipos-conferencia', 'Tipos de Conferência'),
              unavailable('documentos-eletronicos-tipos-documentos-externos', 'Tipos de Documentos Externos'),
              unavailable('documentos-eletronicos-tipos-documentos-internos', 'Tipos de Documentos Internos'),
              unavailable('documentos-eletronicos-tipos-vinculo-documentos', 'Tipos de Vínculos entre Documentos'),
            ],
          },
        ],
      },
      {
        id: 'processos-eletronicos',
        type: 'group',
        label: 'Processos Eletrônicos',
        items: [
          { id: 'processos-lista', type: 'link', label: 'Processos', to: '/processos' },
          unavailable('requerimentos', 'Requerimentos'),
        ],
      },
      {
        id: 'processos-fisicos',
        type: 'group',
        label: 'Processos Físicos',
        items: [
          unavailable('caixa-de-entrada-e-saida', 'Caixa de Entrada e Saída'),
          unavailable('caixa-de-tramitacao-externa', 'Caixa de Tramitação Externa'),
          { id: 'arquivo-processos', type: 'link', label: 'Processos', to: '/arquivo' },
        ],
      },
      unavailable('minhas-permissoes', 'Minhas Permissões'),
      unavailable('solitacoes-alteracao-nivel-acesso', 'Solicitações de Alteração de Nível de Acesso'),
    ],
  },
  {
    id: 'gestao-sistema',
    type: 'group',
    label: 'Gestão e Sistema',
    icon: Settings,
    items: [
      { id: 'programa-gestao', type: 'link', label: 'Programa de Gestão', to: '/dashboard' },
      unavailable('administracao', 'Administração', {
        description: 'O acesso ao Django admin foi bloqueado dentro deste frontend. Use uma tela interna quando ela for portada.',
      }),
      unavailable('auditoria', 'Auditoria'),
    ],
  },
  {
    id: 'ti',
    type: 'group',
    label: 'Tecnologia da Informação',
    icon: Settings,
    items: [
      {
        id: 'ti-moodle',
        type: 'group',
        label: 'Moodle',
        items: [
          {
            id: 'ti-moodle-categorias',
            type: 'link',
            label: 'Categorias Moodle',
            to: '/ti/moodle/categorias/',
            activePrefixes: ['/ti/moodle/categorias', '/ensino/moodle-categorias'],
          },
          {
            id: 'ti-moodle-catalogo',
            type: 'link',
            label: 'Categorias & Cursos (Moodle)',
            to: '/ti/moodle/catalogo/',
            activePrefixes: ['/ti/moodle/catalogo', '/ensino/moodle-categorias-cursos'],
          },
          {
            id: 'ti-moodle-config',
            type: 'link',
            label: 'Central Moodle',
            to: '/ti/moodle/configuracoes/',
            activePrefixes: ['/ti/moodle/configuracoes', '/ensino/moodle-config'],
          },
        ],
      },
      {
        id: 'ti-google-sheets-read',
        type: 'link',
        label: 'Leitura Google Sheets',
        to: '/ti/integracoes/google-sheets',
        activePrefixes: ['/ti/integracoes/google-sheets'],
      },
    ],
  },
  {
    id: 'ensino',
    type: 'group',
    label: 'Ensino',
    icon: GraduationCap,
    items: [
      {
        id: 'alunos-professores',
        type: 'group',
        label: 'Alunos e Professores',
        items: [
          { id: 'alunos-nav', type: 'link', label: 'Alunos', to: '/alunos' },
          { id: 'pedagogia-nav', type: 'link', label: 'Pedagogia', to: '/pedagogia', activePrefixes: ['/pedagogia'] },
          {
            id: 'professores-nav',
            type: 'link',
            label: 'Professores',
            to: { pathname: '/usuarios', search: '?tipo=PROFESSOR' },
            activePrefixes: ['/usuarios'],
          },
        ],
      },
      {
        id: 'cadastros-gerais',
        type: 'group',
        label: 'Cadastros Gerais',
        items: [
          {
            id: 'tipos-componente',
            type: 'link',
            label: 'Tipos de Componente',
            to: '/ensino/tipos-componente/',
            activePrefixes: ['/ensino/tipos-componente'],
          },
          {
            id: 'niveis-ensino',
            type: 'link',
            label: 'Níveis de Ensino',
            to: '/ensino/niveis-ensino/',
            activePrefixes: ['/ensino/niveis-ensino'],
          },
        ],
      },
      {
        id: 'catalogos-cursos',
        type: 'group',
        label: 'Catálogos de Cursos',
        items: [
          {
            id: 'cursos-formacao-superior',
            type: 'link',
            label: 'Cursos itinerantes',
            to: '/ensino/cursoitinerante/',
            activePrefixes: ['/ensino/cursoitinerante', '/cursoitinerante', '/ensino/cursoformacaosuperior', '/cursoformacaosuperior'],
          },
          {
            id: 'areas-cursos',
            type: 'link',
            label: 'Cursos iniciais',
            to: '/ensino/cursoinicial/',
            activePrefixes: ['/ensino/cursoinicial', '/ensino/areacurso'],
          },
          {
            id: 'catalogo-cursos-tecnicos',
            type: 'link',
            label: 'Catálogo de cursos técnicos',
            to: '/ensino/cursotecnico/',
            activePrefixes: ['/ensino/cursotecnico'],
          },
        ],
      },
      {
        id: 'cursos-matrizes-componentes',
        type: 'group',
        label: 'Matriz Curricular',
        items: [
          {
            id: 'eixos-tecnologicos',
            type: 'link',
            label: 'Eixos Tecnológicos',
            to: '/ensino/eixotecnologico/',
            activePrefixes: ['/ensino/eixotecnologico'],
          },
          {
            id: 'ofertas-cursos',
            type: 'link',
            label: 'Ofertas de Curso',
            to: '/ensino/ofertas/',
            activePrefixes: ['/ensino/ofertas'],
          },
          {
            id: 'matrizes-curriculares',
            type: 'link',
            label: 'Matrizes Curriculares',
            to: '/ensino/matrizes-curriculares/',
            activePrefixes: ['/ensino/matrizes-curriculares'],
          },
          {
            id: 'componentes',
            type: 'link',
            label: 'Componentes Curriculares',
            to: '/ensino/componentes/',
            activePrefixes: ['/ensino/componentes', '/componentes'],
          },
          {
            id: 'sica-curricular',
            type: 'link',
            label: 'SICA Curricular',
            to: '/sica',
            activePrefixes: ['/sica'],
          },
          {
            id: 'configurar-curso-wizard',
            type: 'link',
            label: 'Configurar Curso (Wizard)',
            to: '/ensino/configurar-curso',
            activePrefixes: ['/ensino/configurar-curso', '/configurar-curso'],
          },
        ],
      },
      {
        id: 'diario-academico',
        type: 'group',
        label: 'Diário Acadêmico',
        items: [
          {
            id: 'turmas-ensino',
            type: 'link',
            label: 'Turmas',
            to: '/turmas',
            activePrefixes: ['/turmas'],
          },
          {
            id: 'diarios-ensino',
            type: 'link',
            label: 'Diários de Classe',
            to: '/diarios',
            activePrefixes: ['/diarios', '/ensino/diarios'],
          },
          {
            id: 'notas-ensino',
            type: 'link',
            label: 'Notas',
            to: '/ensino/notas',
            activePrefixes: ['/ensino/notas', '/notas'],
          },
          {
            id: 'frequencia-ensino',
            type: 'link',
            label: 'Frequência',
            to: '/ensino/frequencia',
            activePrefixes: ['/ensino/frequencia', '/frequencia'],
          },
        ],
      },
      unavailable('dados-de-ensino', 'Dados de Ensino'),
      unavailable('certificados-enem', 'Certificados ENEM'),
      unavailable('comunicador', 'Comunicador'),
      {
        id: 'diplomas-e-certificados',
        type: 'group',
        label: 'Diplomas e Certificados',
        items: [
          { id: 'certificados-emitidos-nav', type: 'link', label: 'Certificados', to: '/certificados', activePrefixes: ['/certificados'] },
          { id: 'certificados-modelos-nav', type: 'link', label: 'Modelos de Certificado', to: '/certificados/modelos', activePrefixes: ['/certificados/modelos'] },
          { id: 'certificados-historico-nav', type: 'link', label: 'Histórico de Emissão', to: '/certificados/historico', activePrefixes: ['/certificados/historico'] },
          { id: 'certificados-validacao-nav', type: 'link', label: 'Validação Pública', to: '/certificados/validacao', activePrefixes: ['/certificados/validacao'] },
        ],
      },
      unavailable('ead', 'EAD'),
      { id: 'estagios-docentes', type: 'link', label: 'Estágios Docentes', to: '/estagio' },
      unavailable('etep', 'ETEP'),
      { id: 'painel-controle', type: 'link', label: 'Painel de Controle', to: '/dashboard' },
      unavailable('procedimentos-de-apoio', 'Procedimentos de Apoio'),
      { id: 'processos-seletivos', type: 'link', label: 'Processos Seletivos', to: '/inscricoes' },
      unavailable('relatorios-ensino', 'Relatórios'),
      unavailable('programas', 'Programas'),
      unavailable('atas-eletronicas', 'Atas Eletrônicas'),
      unavailable('plano-de-oferta', 'Plano de Oferta'),
      unavailable('regulacao', 'Regulação'),
      unavailable('migracao-de-dados', 'Migração de dados'),
      unavailable('napne', 'Napne'),
      unavailable('variaveis-de-gestao', 'Variáveis de Gestão'),
      unavailable('acervo-academico', 'Acervo Acadêmico'),
      unavailable('atividade-profissional-efetiva', 'Atividade Profissional Efetiva'),
      unavailable('planos-individuais-de-trabalho', 'Planos Individuais de Trabalho'),
      unavailable('laboratorios-remotos', 'Laboratórios Remotos'),
      unavailable('projetos-ensino', 'Projetos'),
      unavailable('ppc', 'PPC'),
      unavailable('pafc', 'PAFC'),
    ],
  },
  {
    id: 'gestao-pessoas',
    type: 'group',
    label: 'Gestão de Pessoas',
    icon: Users,
    items: [
      {
        id: 'servidores',
        type: 'link',
        label: 'Servidores',
        to: '/rh/servidores',
        activePrefixes: ['/rh/servidores'],
      },
      {
        id: 'notificacoes-servidores',
        type: 'link',
        label: 'Notificações',
        to: '/comum/notificacoes',
        activePrefixes: ['/comum/notificacoes'],
      },
      { id: 'setores', type: 'link', label: 'Setores', to: '/rh/setores', activePrefixes: ['/rh/setores'] },
      {
        id: 'administracao-pessoal',
        type: 'group',
        label: 'Administração de Pessoal',
        items: [
          rhUnavailable('organograma', 'Organograma'),
          rhUnavailable('ponto', 'Ponto'),
          rhUnavailable('solicitacoes', 'Solicitações'),
          rhUnavailable('acumulo-de-cargo', 'Acúmulo de Cargo'),
          rhUnavailable('acompanhamento-funcional', 'Acompanhamento Funcional'),
        ],
      },
      {
        id: 'desenvolvimento-pessoal',
        type: 'group',
        label: 'Desenvolvimento de Pessoal',
        items: [
          rhUnavailable('remocao-interna', 'Remoção Interna'),
          rhUnavailable('avaliacao-de-desempenho', 'Avaliação de Desempenho'),
          rhUnavailable('licenca-capacitacao', 'Licença Capacitação'),
          rhUnavailable('pdp', 'PDP'),
          {
            id: 'docentes',
            type: 'link',
            label: 'Docentes',
            to: '/rh/docentes',
            activePrefixes: ['/rh/docentes'],
          },
        ],
      },
      rhUnavailable('atencao-a-saude-do-servidor', 'Atenção à Saúde do Servidor'),
      {
        id: 'cadastros-pessoas',
        type: 'group',
        label: 'Cadastros',
        items: [
          { id: 'instituicoes', type: 'link', label: 'Instituições', to: '/rh/instituicoes', activePrefixes: ['/rh/instituicoes'] },
        ],
      },
      rhUnavailable('variaveis-de-gestao-pessoas', 'Variáveis de Gestão'),
    ],
  },
  {
    id: 'modulos-ativacao',
    type: 'group',
    label: 'Módulos em Ativação',
    icon: Power,
    items: [
      activation('tecnologia-da-informacao', 'Tec. da Informação (ativar)'),
      activation('desenvolvimento-institucional', 'Des. Institucional (ativar)'),
      activation('central-de-servicos', 'Central de Serviços (ativar)'),
      activation('internacionalizacao', 'Internacionalização (ativar)'),
      activation('atividades-estudantis', 'Atividades Estudantis (ativar)'),
      activation('comunicacao-social', 'Comunicação Social (ativar)'),
      activation('seguranca-institucional', 'Segurança Institucional (ativar)'),
      activation('pesquisa', 'Pesquisa (ativar)'),
      activation('extensao', 'Extensão (ativar)'),
    ],
  },
]

