# Generated by Django 6.0.3 on 2026-03-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=180)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('OBRIGATORIO', 'Obrigatorio'), ('OPTATIVO', 'Optativo'), ('PRATICO', 'Pratico')], default='OBRIGATORIO', max_length=20)),
                ('ementa', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente curricular',
                'verbose_name_plural': 'Componentes curriculares',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=40, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estrutura de curso',
                'verbose_name_plural': 'Estruturas de curso',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=60)),
                ('entidade', models.CharField(max_length=120)),
                ('entidade_id', models.PositiveBigIntegerField()),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_configurar_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria configurar curso',
                'verbose_name_plural': 'Auditoria configurar curso',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('codigo', models.CharField(max_length=60)),
                ('versao', models.CharField(max_length=20)),
                ('carga_horaria_total', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('estrutura_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_curriculares', to='configurar_curso.estruturacurso')),
            ],
            options={
                'verbose_name': 'Matriz curricular',
                'verbose_name_plural': 'Matrizes curriculares',
                'ordering': ['nome', 'versao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrizComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField()),
                ('carga_horaria', models.PositiveIntegerField()),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_vinculadas', to='configurar_curso.componentecurricular')),
                ('matriz_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_vinculados', to='configurar_curso.matrizcurricular')),
            ],
            options={
                'verbose_name': 'Vinculo matriz x componente',
                'verbose_name_plural': 'Vinculos matriz x componente',
                'ordering': ['matriz_curricular_id', 'periodo', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=180)),
                ('nome_curto', models.CharField(max_length=80)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EAD', 'EAD'), ('HIBRIDO', 'Hibrido')], default='PRESENCIAL', max_length=20)),
                ('carga_horaria_total', models.PositiveIntegerField()),
                ('situacao', models.CharField(choices=[('EM_CONFIGURACAO', 'Em configuracao'), ('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='EM_CONFIGURACAO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('estrutura_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='configurar_curso.estruturacurso')),
                ('matriz_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='configurar_curso.matrizcurricular')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCursoWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa_atual', models.CharField(choices=[('estrutura', 'Estrutura de curso'), ('matriz', 'Matriz curricular'), ('componentes', 'Componentes'), ('requisitos', 'Requisitos'), ('curso', 'Curso'), ('coordenadores', 'Coordenadores'), ('resumo', 'Resumo'), ('concluido', 'Concluido')], default='estrutura', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido')], default='rascunho', max_length=20)),
                ('payload_parcial', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_curso_wizard', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizards', to='configurar_curso.curso')),
                ('estrutura_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizards', to='configurar_curso.estruturacurso')),
                ('matriz_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizards', to='configurar_curso.matrizcurricular')),
            ],
            options={
                'verbose_name': 'Configuracao de curso (wizard)',
                'verbose_name_plural': 'Configuracoes de curso (wizard)',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisitos', to='configurar_curso.componentecurricular')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_requisito_de', to='configurar_curso.componentecurricular')),
            ],
            options={
                'verbose_name': 'Pre-requisito',
                'verbose_name_plural': 'Pre-requisitos',
                'ordering': ['componente_id', 'requisito_id'],
            },
        ),
        migrations.CreateModel(
            name='CoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_requisitos', to='configurar_curso.componentecurricular')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_co_requisito_de', to='configurar_curso.componentecurricular')),
            ],
            options={
                'verbose_name': 'Co-requisito',
                'verbose_name_plural': 'Co-requisitos',
                'ordering': ['componente_id', 'requisito_id'],
                'constraints': [models.UniqueConstraint(fields=('componente', 'requisito'), name='uniq_config_curso_corequisito'), models.CheckConstraint(condition=models.Q(('componente', models.F('requisito')), _negated=True), name='chk_config_curso_corequisito_no_self')],
            },
        ),
        migrations.CreateModel(
            name='CursoCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_cursos', to='configurar_curso.coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_coordenadores', to='configurar_curso.curso')),
            ],
            options={
                'verbose_name': 'Vinculo curso x coordenador',
                'verbose_name_plural': 'Vinculos curso x coordenador',
                'ordering': ['-principal', '-inicio_vigencia', 'id'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'coordenador', 'inicio_vigencia'), name='uniq_config_curso_coordenador_vigencia'), models.UniqueConstraint(condition=models.Q(('fim_vigencia__isnull', True), ('principal', True)), fields=('curso',), name='uniq_config_curso_coordenador_principal_ativo')],
            },
        ),
        migrations.AddConstraint(
            model_name='matrizcurricular',
            constraint=models.UniqueConstraint(fields=('codigo', 'versao'), name='uniq_config_curso_matriz_codigo_versao'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponente',
            constraint=models.UniqueConstraint(fields=('matriz_curricular', 'componente_curricular'), name='uniq_config_curso_matriz_componente'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponente',
            constraint=models.UniqueConstraint(fields=('matriz_curricular', 'periodo', 'ordem'), name='uniq_config_curso_matriz_periodo_ordem'),
        ),
        migrations.AddConstraint(
            model_name='prerequisito',
            constraint=models.UniqueConstraint(fields=('componente', 'requisito'), name='uniq_config_curso_prerequisito'),
        ),
        migrations.AddConstraint(
            model_name='prerequisito',
            constraint=models.CheckConstraint(condition=models.Q(('componente', models.F('requisito')), _negated=True), name='chk_config_curso_prerequisito_no_self'),
        ),
    ]
