# Generated by Django 6.0.3 on 2026-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_seed_fixed_unidades'),
        ('unidades', '0002_unidade_cidade_unidade_endereco_unidade_uf_and_more'),
    ]

    operations = [
    ]
