/**
 * Playwright script — Cadastro de 50 alunos fictícios
 * Sistema: http://10.255.27.252:5175/processos
 *
 * Execução:
 *   npm init -y && npm install playwright
 *   npx playwright install chromium
 *   node scripts/seed_alunos.js
 */

const { chromium } = require('playwright');

// ─── Base de dados dos 50 alunos ─────────────────────────────────────────────

const ALUNOS = [
  // ── MODALIDADE: Remoto (17) | POLO: Sede (6), Rio Branco (6), Flora Calheiros (5) ──
  {
    nome: 'Ana Beatriz Cavalcante Souza',
    cpf: '123.456.789-09',
    rg: '1234567',
    nascimento: '2005-03-12',
    sexo: 'Feminino',
    email: 'ana.cavalcante.souza@email.com',
    telefone: '(82) 98712-3401',
    endereco: { rua: 'Rua das Flores', numero: '45', bairro: 'Centro', cidade: 'Maceió', estado: 'AL', cep: '57000-100', complemento: 'Apto 201' },
    matricula: 'REM2024001',
    curso: 'Técnico em Informática',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'INF-A',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Cláudia Cavalcante Souza', cpf: '987.654.321-00', parentesco: 'Mãe', telefone: '(82) 98712-3400', email: 'claudia.cavalcante@email.com' },
    resp2: { nome: 'Roberto Souza Cavalcante', cpf: '741.852.963-10', parentesco: 'Pai', telefone: '(82) 98712-3399', email: 'roberto.souza.cav@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Aluna dedicada, excelente desempenho em programação.',
    obs_administrativa: 'Documentação completa entregue.',
  },
  {
    nome: 'Bruno Henrique Ferreira Lima',
    cpf: '234.567.890-10',
    rg: '2345678',
    nascimento: '2004-07-22',
    sexo: 'Masculino',
    email: 'bruno.ferreira.lima@email.com',
    telefone: '(82) 98712-3402',
    endereco: { rua: 'Av. Presidente Médici', numero: '120', bairro: 'Farol', cidade: 'Maceió', estado: 'AL', cep: '57052-300', complemento: '' },
    matricula: 'REM2024002',
    curso: 'Técnico em Administração',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'ADM-B',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Em análise',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Maria Lima Ferreira', cpf: '852.963.741-20', parentesco: 'Mãe', telefone: '(82) 98712-3410', email: 'maria.lima.ferreira@email.com' },
    resp2: { nome: 'José Ferreira Lima', cpf: '369.258.147-30', parentesco: 'Pai', telefone: '(82) 98712-3411', email: 'jose.ferreira.lima@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Farol/Centro',
    obs_academica: 'Bom desempenho em disciplinas administrativas.',
    obs_administrativa: 'Pendente comprovante de residência.',
  },
  {
    nome: 'Carla Renata Oliveira Mendes',
    cpf: '345.678.901-21',
    rg: '3456789',
    nascimento: '2003-11-05',
    sexo: 'Feminino',
    email: 'carla.oliveira.mendes@email.com',
    telefone: '(82) 98712-3403',
    endereco: { rua: 'Rua Barão de Maceió', numero: '78', bairro: 'Jaraguá', cidade: 'Maceió', estado: 'AL', cep: '57025-010', complemento: 'Casa 2' },
    matricula: 'REM2024003',
    curso: 'Técnico em Enfermagem',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'ENF-A',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Concluinte',
    resp1: { nome: 'Sandra Mendes Oliveira', cpf: '159.753.486-40', parentesco: 'Mãe', telefone: '(82) 98712-3412', email: 'sandra.mendes@email.com' },
    resp2: { nome: 'Paulo Oliveira Mendes', cpf: '486.159.753-50', parentesco: 'Pai', telefone: '(82) 98712-3413', email: 'paulo.oliveira.m@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Concluindo o curso com excelência. Candidata a prêmio de destaque.',
    obs_administrativa: 'Documentação em ordem.',
  },
  {
    nome: 'Diego Augusto Barbosa Neto',
    cpf: '456.789.012-32',
    rg: '4567890',
    nascimento: '2006-01-18',
    sexo: 'Masculino',
    email: 'diego.barbosa.neto@email.com',
    telefone: '(82) 98712-3404',
    endereco: { rua: 'Rua do Comércio', numero: '200', bairro: 'Pinheiro', cidade: 'Maceió', estado: 'AL', cep: '57057-000', complemento: 'Bloco B Ap 303' },
    matricula: 'REM2024004',
    curso: 'Técnico em Logística',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'LOG-A',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Pendente de documentação',
    situacao_academica: 'Aguardando documentação',
    resp1: { nome: 'Fátima Barbosa Neto', cpf: '753.159.486-60', parentesco: 'Mãe', telefone: '(82) 98712-3414', email: 'fatima.barbosa@email.com' },
    resp2: { nome: 'Carlos Neto Barbosa', cpf: '321.654.987-70', parentesco: 'Pai', telefone: '(82) 98712-3415', email: 'carlos.neto.b@email.com' },
    necessidade_especial: 'Dislexia — acompanhamento pedagógico',
    transporte: 'Utiliza transporte escolar — linha Pinheiro/Centro',
    obs_academica: 'Necessita acompanhamento especial em leitura e interpretação.',
    obs_administrativa: 'Aguardando laudo médico.',
  },
  {
    nome: 'Elaine Cristina Pereira dos Santos',
    cpf: '567.890.123-43',
    rg: '5678901',
    nascimento: '2005-09-30',
    sexo: 'Feminino',
    email: 'elaine.pereira.santos@email.com',
    telefone: '(82) 98712-3405',
    endereco: { rua: 'Av. Fernandes Lima', numero: '550', bairro: 'Gruta de Lourdes', cidade: 'Maceió', estado: 'AL', cep: '57052-000', complemento: '' },
    matricula: 'REM2024005',
    curso: 'Técnico em Segurança do Trabalho',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'SEG-A',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Aguardando matrícula',
    situacao_academica: 'Em regularização',
    resp1: { nome: 'Rosane Santos Pereira', cpf: '147.258.369-80', parentesco: 'Mãe', telefone: '(82) 98712-3416', email: 'rosane.santos@email.com' },
    resp2: { nome: 'Antônio Pereira dos Santos', cpf: '258.369.147-90', parentesco: 'Pai', telefone: '(82) 98712-3417', email: 'antonio.pereira.s@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Interesse em estágio na área de segurança.',
    obs_administrativa: 'Em processo de regularização de documentos.',
  },
  {
    nome: 'Felipe Rodrigues Almeida Costa',
    cpf: '678.901.234-54',
    rg: '6789012',
    nascimento: '2004-04-14',
    sexo: 'Masculino',
    email: 'felipe.almeida.costa@email.com',
    telefone: '(82) 98712-3406',
    endereco: { rua: 'Rua Dr. Antônio Gomes de Barros', numero: '33', bairro: 'Mangabeiras', cidade: 'Maceió', estado: 'AL', cep: '57037-380', complemento: 'Apto 102' },
    matricula: 'REM2024006',
    curso: 'Técnico em Contabilidade',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'CONT-A',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Vera Costa Almeida', cpf: '963.852.741-00', parentesco: 'Mãe', telefone: '(82) 98712-3418', email: 'vera.costa@email.com' },
    resp2: { nome: 'Marcos Almeida Costa', cpf: '741.963.852-10', parentesco: 'Pai', telefone: '(82) 98712-3419', email: 'marcos.almeida.c@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Participante ativo do clube de matemática.',
    obs_administrativa: 'Bolsista — documentação anual em dia.',
  },
  {
    nome: 'Gabriela Nascimento Teixeira',
    cpf: '789.012.345-65',
    rg: '7890123',
    nascimento: '1998-12-20',
    sexo: 'Feminino',
    email: 'gabriela.nascimento.teix@email.com',
    telefone: '(82) 98712-3407',
    endereco: { rua: 'Rua São Paulo', numero: '88', bairro: 'Centro', cidade: 'Rio Branco', estado: 'AC', cep: '69900-050', complemento: '' },
    matricula: 'REM2024007',
    curso: 'Técnico em Recursos Humanos',
    modalidade: 'Remoto',
    polo: 'Rio Branco',
    turma: 'RH-A',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Luciana Teixeira Nascimento', cpf: '852.741.963-20', parentesco: 'Mãe', telefone: '(68) 98712-3420', email: 'luciana.teixeira@email.com' },
    resp2: { nome: 'Fernando Nascimento Teixeira', cpf: '369.741.852-30', parentesco: 'Pai', telefone: '(68) 98712-3421', email: 'fernando.nasc@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Aluna adulta retornando aos estudos após pausa profissional.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Henrique Vieira Carvalho',
    cpf: '890.123.456-76',
    rg: '8901234',
    nascimento: '2000-05-08',
    sexo: 'Masculino',
    email: 'henrique.vieira.carvalho@email.com',
    telefone: '(68) 98712-3408',
    endereco: { rua: 'Av. Brasil', numero: '999', bairro: 'Bosque', cidade: 'Rio Branco', estado: 'AC', cep: '69900-100', complemento: 'Bloco C' },
    matricula: 'REM2024008',
    curso: 'Técnico em Meio Ambiente',
    modalidade: 'Remoto',
    polo: 'Rio Branco',
    turma: 'MEIO-A',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Aprovado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Cristina Carvalho Vieira', cpf: '258.147.369-40', parentesco: 'Mãe', telefone: '(68) 98712-3422', email: 'cristina.carvalho@email.com' },
    resp2: { nome: 'Eduardo Vieira Carvalho', cpf: '147.369.258-50', parentesco: 'Pai', telefone: '(68) 98712-3423', email: 'eduardo.vieira@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Bosque/Centro',
    obs_academica: 'Engajado em projetos de sustentabilidade.',
    obs_administrativa: 'Bolsista parcial.',
  },
  {
    nome: 'Isabela Monteiro Figueiredo',
    cpf: '901.234.567-87',
    rg: '9012345',
    nascimento: '2003-08-15',
    sexo: 'Feminino',
    email: 'isabela.monteiro.fig@email.com',
    telefone: '(68) 98712-3409',
    endereco: { rua: 'Rua Epaminondas Jácome', numero: '210', bairro: 'Montanhês', cidade: 'Rio Branco', estado: 'AC', cep: '69900-200', complemento: '' },
    matricula: 'REM2024009',
    curso: 'Técnico em Agropecuária',
    modalidade: 'Remoto',
    polo: 'Rio Branco',
    turma: 'AGRO-A',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Em análise',
    situacao_academica: 'Em transferência',
    resp1: { nome: 'Beatriz Figueiredo Monteiro', cpf: '741.258.963-60', parentesco: 'Mãe', telefone: '(68) 98712-3424', email: 'beatriz.figueiredo@email.com' },
    resp2: { nome: 'Ricardo Monteiro Figueiredo', cpf: '963.258.741-70', parentesco: 'Pai', telefone: '(68) 98712-3425', email: 'ricardo.monteiro@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Transferência da rede estadual em andamento.',
    obs_administrativa: 'Aguardando histórico escolar original.',
  },
  {
    nome: 'João Pedro Sousa Ramos',
    cpf: '012.345.678-98',
    rg: '0123456',
    nascimento: '2005-02-27',
    sexo: 'Masculino',
    email: 'joao.sousa.ramos@email.com',
    telefone: '(68) 98712-3430',
    endereco: { rua: 'Rua Marechal Hermes', numero: '67', bairro: 'Cadeia Velha', cidade: 'Rio Branco', estado: 'AC', cep: '69900-300', complemento: 'Casa fundos' },
    matricula: 'REM2024010',
    curso: 'Técnico em Eletrotécnica',
    modalidade: 'Remoto',
    polo: 'Rio Branco',
    turma: 'ELET-A',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Pendente de documentação',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Patrícia Ramos Sousa', cpf: '321.741.852-00', parentesco: 'Mãe', telefone: '(68) 98712-3426', email: 'patricia.ramos@email.com' },
    resp2: { nome: 'Leandro Sousa Ramos', cpf: '852.321.741-10', parentesco: 'Pai', telefone: '(68) 98712-3427', email: 'leandro.sousa.r@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Cadeia Velha/Centro',
    obs_academica: 'Interesse em robótica e automação.',
    obs_administrativa: 'Pendente certidão de nascimento.',
  },
  {
    nome: 'Karina Lopes Azevedo',
    cpf: '111.222.333-96',
    rg: '1112223',
    nascimento: '2004-06-10',
    sexo: 'Feminino',
    email: 'karina.lopes.azevedo@email.com',
    telefone: '(68) 98712-3431',
    endereco: { rua: 'Rua Floriano Peixoto', numero: '134', bairro: 'Centro', cidade: 'Rio Branco', estado: 'AC', cep: '69900-005', complemento: 'Apto 405' },
    matricula: 'REM2024011',
    curso: 'Técnico em Informática',
    modalidade: 'Remoto',
    polo: 'Rio Branco',
    turma: 'INF-B',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Simone Azevedo Lopes', cpf: '444.555.666-06', parentesco: 'Mãe', telefone: '(68) 98712-3428', email: 'simone.azevedo@email.com' },
    resp2: { nome: 'Gilberto Lopes Azevedo', cpf: '777.888.999-16', parentesco: 'Pai', telefone: '(68) 98712-3429', email: 'gilberto.lopes@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Destaque em projetos web.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Leonardo Andrade Pinto',
    cpf: '222.333.444-07',
    rg: '2223334',
    nascimento: '2002-10-03',
    sexo: 'Masculino',
    email: 'leonardo.andrade.pinto@email.com',
    telefone: '(82) 98712-3432',
    endereco: { rua: 'Rua Sete de Setembro', numero: '456', bairro: 'Centro', cidade: 'União dos Palmares', estado: 'AL', cep: '57400-000', complemento: '' },
    matricula: 'REM2024012',
    curso: 'Técnico em Administração',
    modalidade: 'Remoto',
    polo: 'Flora Calheiros',
    turma: 'ADM-C',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Aprovado',
    situacao_academica: 'Concluinte',
    resp1: { nome: 'Márcia Pinto Andrade', cpf: '555.666.777-17', parentesco: 'Mãe', telefone: '(82) 98712-3433', email: 'marcia.pinto@email.com' },
    resp2: { nome: 'Sérgio Andrade Pinto', cpf: '888.999.000-27', parentesco: 'Pai', telefone: '(82) 98712-3434', email: 'sergio.andrade@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha União dos Palmares/Sede',
    obs_academica: 'Finaliza o curso este semestre. Excelente histórico.',
    obs_administrativa: 'Solicita diploma digital.',
  },
  {
    nome: 'Mariana Cunha Brandão',
    cpf: '333.444.555-18',
    rg: '3334445',
    nascimento: '2006-03-25',
    sexo: 'Feminino',
    email: 'mariana.cunha.brandao@email.com',
    telefone: '(82) 98712-3435',
    endereco: { rua: 'Av. Getúlio Vargas', numero: '789', bairro: 'Vila Nova', cidade: 'União dos Palmares', estado: 'AL', cep: '57400-100', complemento: 'Casa 3' },
    matricula: 'REM2024013',
    curso: 'Técnico em Enfermagem',
    modalidade: 'Remoto',
    polo: 'Flora Calheiros',
    turma: 'ENF-B',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Joana Brandão Cunha', cpf: '666.777.888-28', parentesco: 'Mãe', telefone: '(82) 98712-3436', email: 'joana.brandao@email.com' },
    resp2: { nome: 'Paulo Cunha Brandão', cpf: '999.000.111-38', parentesco: 'Pai', telefone: '(82) 98712-3437', email: 'paulo.cunha.b@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Voluntária em posto de saúde local.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Nathan Borges Queiroz',
    cpf: '444.555.666-29',
    rg: '4445556',
    nascimento: '2005-11-11',
    sexo: 'Masculino',
    email: 'nathan.borges.queiroz@email.com',
    telefone: '(82) 98712-3438',
    endereco: { rua: 'Rua Coronel João Pessoa', numero: '321', bairro: 'Bom Jesus', cidade: 'Palmeira dos Índios', estado: 'AL', cep: '57601-000', complemento: '' },
    matricula: 'REM2024014',
    curso: 'Técnico em Segurança do Trabalho',
    modalidade: 'Remoto',
    polo: 'Flora Calheiros',
    turma: 'SEG-B',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Indeferido',
    situacao_academica: 'Trancado',
    resp1: { nome: 'Tereza Queiroz Borges', cpf: '000.111.222-39', parentesco: 'Mãe', telefone: '(82) 98712-3439', email: 'tereza.queiroz@email.com' },
    resp2: { nome: 'Benedito Borges Queiroz', cpf: '111.000.222-49', parentesco: 'Pai', telefone: '(82) 98712-3440', email: 'benedito.borges@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Palmeira/Sede',
    obs_academica: 'Processo indeferido por pendência documental; trancamento solicitado.',
    obs_administrativa: 'Recurso administrativo em análise.',
  },
  {
    nome: 'Olivia Souza Batista',
    cpf: '555.666.777-30',
    rg: '5556667',
    nascimento: '2004-01-07',
    sexo: 'Feminino',
    email: 'olivia.souza.batista@email.com',
    telefone: '(82) 98712-3441',
    endereco: { rua: 'Rua XV de Novembro', numero: '55', bairro: 'Centro', cidade: 'Palmeira dos Índios', estado: 'AL', cep: '57601-010', complemento: 'Apto 12' },
    matricula: 'REM2024015',
    curso: 'Técnico em Logística',
    modalidade: 'Remoto',
    polo: 'Flora Calheiros',
    turma: 'LOG-B',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Carmen Batista Souza', cpf: '222.111.333-59', parentesco: 'Mãe', telefone: '(82) 98712-3442', email: 'carmen.batista@email.com' },
    resp2: { nome: 'Ernesto Souza Batista', cpf: '333.222.111-69', parentesco: 'Pai', telefone: '(82) 98712-3443', email: 'ernesto.souza.b@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Participante de projeto de logística reversa.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Pedro Augusto Melo Cavalcante',
    cpf: '666.777.888-41',
    rg: '6667778',
    nascimento: '2003-09-19',
    sexo: 'Masculino',
    email: 'pedro.melo.cavalcante@email.com',
    telefone: '(82) 98712-3444',
    endereco: { rua: 'Av. Durval Guimarães', numero: '1200', bairro: 'Jatiúca', cidade: 'Maceió', estado: 'AL', cep: '57036-000', complemento: 'Bloco A' },
    matricula: 'REM2024016',
    curso: 'Técnico em Contabilidade',
    modalidade: 'Remoto',
    polo: 'Flora Calheiros',
    turma: 'CONT-B',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Em análise',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Lucélia Cavalcante Melo', cpf: '444.333.222-79', parentesco: 'Mãe', telefone: '(82) 98712-3445', email: 'lucelia.cavalcante@email.com' },
    resp2: { nome: 'Rogério Melo Cavalcante', cpf: '555.444.333-89', parentesco: 'Pai', telefone: '(82) 98712-3446', email: 'rogerio.melo@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Jatiúca/Centro',
    obs_academica: 'Interesse em abrir próprio negócio.',
    obs_administrativa: 'Documentação quase completa.',
  },
  {
    nome: 'Rafaela Duarte Mendonça',
    cpf: '777.888.999-52',
    rg: '7778889',
    nascimento: '2005-07-04',
    sexo: 'Feminino',
    email: 'rafaela.duarte.mendonca@email.com',
    telefone: '(82) 98712-3447',
    endereco: { rua: 'Rua Comendador Palmeira', numero: '17', bairro: 'Levada', cidade: 'Maceió', estado: 'AL', cep: '57017-000', complemento: '' },
    matricula: 'REM2024017',
    curso: 'Técnico em Recursos Humanos',
    modalidade: 'Remoto',
    polo: 'Sede',
    turma: 'RH-B',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Adriana Mendonça Duarte', cpf: '666.555.444-99', parentesco: 'Mãe', telefone: '(82) 98712-3448', email: 'adriana.mendonca@email.com' },
    resp2: { nome: 'Flávio Duarte Mendonça', cpf: '777.666.555-09', parentesco: 'Pai', telefone: '(82) 98712-3449', email: 'flavio.duarte@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Estagiária em empresa de recrutamento.',
    obs_administrativa: 'Documentação completa.',
  },

  // ── MODALIDADE: Técnico (17) | POLO: Sede (6), Rio Branco (6), Flora Calheiros (5) ──
  {
    nome: 'Samuel Gomes Rocha',
    cpf: '888.999.000-63',
    rg: '8889990',
    nascimento: '2004-12-01',
    sexo: 'Masculino',
    email: 'samuel.gomes.rocha@email.com',
    telefone: '(82) 98712-3450',
    endereco: { rua: 'Rua Boa Vista', numero: '300', bairro: 'Benedito Bentes', cidade: 'Maceió', estado: 'AL', cep: '57085-000', complemento: '' },
    matricula: 'TEC2024001',
    curso: 'Técnico em Eletrotécnica',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'ELET-B',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Noêmia Rocha Gomes', cpf: '999.888.777-73', parentesco: 'Mãe', telefone: '(82) 98712-3451', email: 'noemia.rocha@email.com' },
    resp2: { nome: 'Davi Gomes Rocha', cpf: '000.999.888-83', parentesco: 'Pai', telefone: '(82) 98712-3452', email: 'davi.gomes.r@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Destaque em instalações elétricas residenciais.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Tatiana Correia Vilaça',
    cpf: '100.200.300-40',
    rg: '1002003',
    nascimento: '2003-04-29',
    sexo: 'Feminino',
    email: 'tatiana.correia.vilaca@email.com',
    telefone: '(82) 98712-3453',
    endereco: { rua: 'Rua Silvio Romero', numero: '112', bairro: 'Pitanguinha', cidade: 'Maceió', estado: 'AL', cep: '57071-000', complemento: 'Casa 01' },
    matricula: 'TEC2024002',
    curso: 'Técnico em Agropecuária',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'AGRO-B',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Aprovado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Helena Vilaça Correia', cpf: '200.300.400-50', parentesco: 'Mãe', telefone: '(82) 98712-3454', email: 'helena.vilaca@email.com' },
    resp2: { nome: 'Otoniel Correia Vilaça', cpf: '300.400.500-60', parentesco: 'Pai', telefone: '(82) 98712-3455', email: 'otoniel.correia@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Pitanguinha/Sede',
    obs_academica: 'Interesse em zootecnia e produção animal.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Ulisses Barros Fontes',
    cpf: '200.300.400-61',
    rg: '2003004',
    nascimento: '2005-08-08',
    sexo: 'Masculino',
    email: 'ulisses.barros.fontes@email.com',
    telefone: '(82) 98712-3456',
    endereco: { rua: 'Av. Siqueira Campos', numero: '678', bairro: 'Poço', cidade: 'Maceió', estado: 'AL', cep: '57025-400', complemento: 'Apto 501' },
    matricula: 'TEC2024003',
    curso: 'Técnico em Meio Ambiente',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'MEIO-B',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Em análise',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Cleide Fontes Barros', cpf: '400.500.600-71', parentesco: 'Mãe', telefone: '(82) 98712-3457', email: 'cleide.fontes@email.com' },
    resp2: { nome: 'Igor Barros Fontes', cpf: '500.600.700-81', parentesco: 'Pai', telefone: '(82) 98712-3458', email: 'igor.barros.f@email.com' },
    necessidade_especial: 'TDAH — relatório pedagógico anexado',
    transporte: 'Não utiliza',
    obs_academica: 'Relatório de TDAH encaminhado ao setor pedagógico.',
    obs_administrativa: 'Acompanhamento semestral obrigatório.',
  },
  {
    nome: 'Vanessa Lima Guimarães',
    cpf: '300.400.500-72',
    rg: '3004005',
    nascimento: '2004-02-18',
    sexo: 'Feminino',
    email: 'vanessa.lima.guimaraes@email.com',
    telefone: '(82) 98712-3459',
    endereco: { rua: 'Rua da Paz', numero: '90', bairro: 'Vergel do Lago', cidade: 'Maceió', estado: 'AL', cep: '57055-000', complemento: '' },
    matricula: 'TEC2024004',
    curso: 'Técnico em Informática',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'INF-C',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Rosa Guimarães Lima', cpf: '600.700.800-82', parentesco: 'Mãe', telefone: '(82) 98712-3460', email: 'rosa.guimaraes@email.com' },
    resp2: { nome: 'Antônio Lima Guimarães', cpf: '700.800.900-92', parentesco: 'Pai', telefone: '(82) 98712-3461', email: 'antonio.lima.g@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Representante de turma.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Wagner Pires de Souza',
    cpf: '400.500.600-83',
    rg: '4005006',
    nascimento: '2002-06-30',
    sexo: 'Masculino',
    email: 'wagner.pires.souza@email.com',
    telefone: '(82) 98712-3462',
    endereco: { rua: 'Rua Jacarandá', numero: '500', bairro: 'Santos Dumont', cidade: 'Maceió', estado: 'AL', cep: '57083-000', complemento: 'Casa B' },
    matricula: 'TEC2024005',
    curso: 'Técnico em Administração',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'ADM-D',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Aguardando matrícula',
    situacao_academica: 'Em regularização',
    resp1: { nome: 'Flávia Souza Pires', cpf: '800.900.100-02', parentesco: 'Mãe', telefone: '(82) 98712-3463', email: 'flavia.souza.p@email.com' },
    resp2: { nome: 'Nilson Pires de Souza', cpf: '900.100.200-12', parentesco: 'Pai', telefone: '(82) 98712-3464', email: 'nilson.pires@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Santos Dumont/Centro',
    obs_academica: 'Regularizando histórico escolar anterior.',
    obs_administrativa: 'Pendente declaração de conclusão do ensino médio.',
  },
  {
    nome: 'Ximena Castro Rezende',
    cpf: '500.600.700-94',
    rg: '5006007',
    nascimento: '2006-10-16',
    sexo: 'Feminino',
    email: 'ximena.castro.rezende@email.com',
    telefone: '(82) 98712-3465',
    endereco: { rua: 'Rua dos Coqueiros', numero: '25', bairro: 'Petrópolis', cidade: 'Maceió', estado: 'AL', cep: '57035-000', complemento: '' },
    matricula: 'TEC2024006',
    curso: 'Técnico em Enfermagem',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'ENF-C',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Lúcia Rezende Castro', cpf: '100.010.200-22', parentesco: 'Mãe', telefone: '(82) 98712-3466', email: 'lucia.rezende@email.com' },
    resp2: { nome: 'Gilson Castro Rezende', cpf: '200.020.300-32', parentesco: 'Pai', telefone: '(82) 98712-3467', email: 'gilson.castro@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Participante do projeto saúde na escola.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Yuri Alves Machado',
    cpf: '600.700.800-05',
    rg: '6007008',
    nascimento: '2003-03-03',
    sexo: 'Masculino',
    email: 'yuri.alves.machado@email.com',
    telefone: '(68) 98712-3468',
    endereco: { rua: 'Rua Hugo Carneiro', numero: '444', bairro: 'Aviário', cidade: 'Rio Branco', estado: 'AC', cep: '69900-400', complemento: 'Apto 202' },
    matricula: 'TEC2024007',
    curso: 'Técnico em Segurança do Trabalho',
    modalidade: 'Técnico',
    polo: 'Rio Branco',
    turma: 'SEG-C',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Sueli Machado Alves', cpf: '300.030.400-42', parentesco: 'Mãe', telefone: '(68) 98712-3469', email: 'sueli.machado@email.com' },
    resp2: { nome: 'Roberto Alves Machado', cpf: '400.040.500-52', parentesco: 'Pai', telefone: '(68) 98712-3470', email: 'roberto.alves.m@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Realiza estágio em obra de construção civil.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Zara Ferreira Couto',
    cpf: '700.800.900-16',
    rg: '7008009',
    nascimento: '2004-05-21',
    sexo: 'Feminino',
    email: 'zara.ferreira.couto@email.com',
    telefone: '(68) 98712-3471',
    endereco: { rua: 'Rua do Aviário', numero: '88', bairro: 'Aviário', cidade: 'Rio Branco', estado: 'AC', cep: '69900-410', complemento: '' },
    matricula: 'TEC2024008',
    curso: 'Técnico em Logística',
    modalidade: 'Técnico',
    polo: 'Rio Branco',
    turma: 'LOG-C',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Marise Couto Ferreira', cpf: '500.050.600-62', parentesco: 'Mãe', telefone: '(68) 98712-3472', email: 'marise.couto@email.com' },
    resp2: { nome: 'Álvaro Ferreira Couto', cpf: '600.060.700-72', parentesco: 'Pai', telefone: '(68) 98712-3473', email: 'alvaro.ferreira.c@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Aviário/Centro',
    obs_academica: 'Coordena grupo de estudos de logística.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Artur Nascimento Faria',
    cpf: '800.900.100-27',
    rg: '8009001',
    nascimento: '2001-11-14',
    sexo: 'Masculino',
    email: 'artur.nascimento.faria@email.com',
    telefone: '(68) 98712-3474',
    endereco: { rua: 'Rua Benjamin Constant', numero: '560', bairro: 'Centro', cidade: 'Rio Branco', estado: 'AC', cep: '69900-060', complemento: 'Sala 3' },
    matricula: 'TEC2024009',
    curso: 'Técnico em Contabilidade',
    modalidade: 'Técnico',
    polo: 'Rio Branco',
    turma: 'CONT-C',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Pendente de documentação',
    situacao_academica: 'Aguardando documentação',
    resp1: { nome: 'Valdete Faria Nascimento', cpf: '700.070.800-82', parentesco: 'Mãe', telefone: '(68) 98712-3475', email: 'valdete.faria@email.com' },
    resp2: { nome: 'Cláudio Nascimento Faria', cpf: '800.080.900-92', parentesco: 'Pai', telefone: '(68) 98712-3476', email: 'claudio.nasc.f@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Trabalha durante o dia; curso noturno ideal.',
    obs_administrativa: 'Pendente comprovante de trabalho para bolsa.',
  },
  {
    nome: 'Brenda Marques Ribeiro',
    cpf: '900.100.200-38',
    rg: '9001002',
    nascimento: '2005-01-28',
    sexo: 'Feminino',
    email: 'brenda.marques.ribeiro@email.com',
    telefone: '(68) 98712-3477',
    endereco: { rua: 'Rua Valério Magalhães', numero: '70', bairro: 'Cadeia Nova', cidade: 'Rio Branco', estado: 'AC', cep: '69900-500', complemento: 'Casa fundos' },
    matricula: 'TEC2024010',
    curso: 'Técnico em Recursos Humanos',
    modalidade: 'Técnico',
    polo: 'Rio Branco',
    turma: 'RH-C',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Em análise',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Ivone Ribeiro Marques', cpf: '111.121.131-48', parentesco: 'Mãe', telefone: '(68) 98712-3478', email: 'ivone.ribeiro@email.com' },
    resp2: { nome: 'Cícero Marques Ribeiro', cpf: '222.232.242-58', parentesco: 'Pai', telefone: '(68) 98712-3479', email: 'cicero.marques@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Interesse em gestão de pessoas e liderança.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'César Eduardo Matos Leal',
    cpf: '101.111.121-59',
    rg: '1011112',
    nascimento: '2003-07-07',
    sexo: 'Masculino',
    email: 'cesar.matos.leal@email.com',
    telefone: '(68) 98712-3480',
    endereco: { rua: 'Av. Antônio da Rocha Viana', numero: '1500', bairro: 'Calafate', cidade: 'Rio Branco', estado: 'AC', cep: '69900-600', complemento: '' },
    matricula: 'TEC2024011',
    curso: 'Técnico em Eletrotécnica',
    modalidade: 'Técnico',
    polo: 'Rio Branco',
    turma: 'ELET-C',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Nadia Leal Matos', cpf: '333.343.353-69', parentesco: 'Mãe', telefone: '(68) 98712-3481', email: 'nadia.leal@email.com' },
    resp2: { nome: 'Romildo Matos Leal', cpf: '444.454.464-79', parentesco: 'Pai', telefone: '(68) 98712-3482', email: 'romildo.matos@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Calafate/Centro',
    obs_academica: 'Participante do laboratório de automação.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Daniela Freitas Santana',
    cpf: '202.212.222-60',
    rg: '2022122',
    nascimento: '2004-09-09',
    sexo: 'Feminino',
    email: 'daniela.freitas.santana@email.com',
    telefone: '(82) 98712-3483',
    endereco: { rua: 'Rua do Progresso', numero: '143', bairro: 'Pedra Fina', cidade: 'Murici', estado: 'AL', cep: '57820-000', complemento: '' },
    matricula: 'TEC2024012',
    curso: 'Técnico em Agropecuária',
    modalidade: 'Técnico',
    polo: 'Flora Calheiros',
    turma: 'AGRO-C',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Aprovado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Edilene Santana Freitas', cpf: '555.565.575-89', parentesco: 'Mãe', telefone: '(82) 98712-3484', email: 'edilene.santana@email.com' },
    resp2: { nome: 'Jacinto Freitas Santana', cpf: '666.676.686-99', parentesco: 'Pai', telefone: '(82) 98712-3485', email: 'jacinto.freitas@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Murici/Sede',
    obs_academica: 'Produz hortaliças no sítio da família.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Evandro Soares Pimentel',
    cpf: '303.313.323-71',
    rg: '3033133',
    nascimento: '2002-04-04',
    sexo: 'Masculino',
    email: 'evandro.soares.pimentel@email.com',
    telefone: '(82) 98712-3486',
    endereco: { rua: 'Rua Joaquim Nabuco', numero: '87', bairro: 'Centro', cidade: 'Murici', estado: 'AL', cep: '57820-010', complemento: 'Ap 5' },
    matricula: 'TEC2024013',
    curso: 'Técnico em Meio Ambiente',
    modalidade: 'Técnico',
    polo: 'Flora Calheiros',
    turma: 'MEIO-C',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Dulce Pimentel Soares', cpf: '777.787.797-09', parentesco: 'Mãe', telefone: '(82) 98712-3487', email: 'dulce.pimentel@email.com' },
    resp2: { nome: 'Hélio Soares Pimentel', cpf: '888.898.808-19', parentesco: 'Pai', telefone: '(82) 98712-3488', email: 'helio.soares.p@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Pesquisador voluntário de fauna local.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Fabiana Rocha Coutinho',
    cpf: '404.414.424-82',
    rg: '4044144',
    nascimento: '2005-12-12',
    sexo: 'Feminino',
    email: 'fabiana.rocha.coutinho@email.com',
    telefone: '(82) 98712-3489',
    endereco: { rua: 'Rua Tiradentes', numero: '234', bairro: 'Alto da Boa Vista', cidade: 'Atalaia', estado: 'AL', cep: '57600-000', complemento: '' },
    matricula: 'TEC2024014',
    curso: 'Técnico em Informática',
    modalidade: 'Técnico',
    polo: 'Flora Calheiros',
    turma: 'INF-D',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Em análise',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Elza Coutinho Rocha', cpf: '999.909.919-29', parentesco: 'Mãe', telefone: '(82) 98712-3490', email: 'elza.coutinho@email.com' },
    resp2: { nome: 'Manoel Rocha Coutinho', cpf: '101.010.111-39', parentesco: 'Pai', telefone: '(82) 98712-3491', email: 'manoel.rocha.c@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Atalaia/Sede',
    obs_academica: 'Destaque em programação web.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Gustavo Henrique Teles Maia',
    cpf: '505.515.525-93',
    rg: '5055155',
    nascimento: '2003-06-17',
    sexo: 'Masculino',
    email: 'gustavo.teles.maia@email.com',
    telefone: '(82) 98712-3492',
    endereco: { rua: 'Av. Comendador Leão', numero: '670', bairro: 'Jaraguá', cidade: 'Maceió', estado: 'AL', cep: '57025-020', complemento: 'Sala 2' },
    matricula: 'TEC2024015',
    curso: 'Técnico em Administração',
    modalidade: 'Técnico',
    polo: 'Flora Calheiros',
    turma: 'ADM-E',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Concluinte',
    resp1: { nome: 'Selma Maia Teles', cpf: '202.020.212-49', parentesco: 'Mãe', telefone: '(82) 98712-3493', email: 'selma.maia@email.com' },
    resp2: { nome: 'Jânio Teles Maia', cpf: '303.030.313-59', parentesco: 'Pai', telefone: '(82) 98712-3494', email: 'janio.teles@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Concluindo com distinção. Aprovado em processo seletivo de trainee.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Helena Pacheco Drummond',
    cpf: '606.616.626-04',
    rg: '6066166',
    nascimento: '2004-08-23',
    sexo: 'Feminino',
    email: 'helena.pacheco.drummond@email.com',
    telefone: '(82) 98712-3495',
    endereco: { rua: 'Rua João Pessoa', numero: '19', bairro: 'Centro', cidade: 'Maceió', estado: 'AL', cep: '57020-000', complemento: 'Apto 801' },
    matricula: 'TEC2024016',
    curso: 'Técnico em Enfermagem',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'ENF-D',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Olga Drummond Pacheco', cpf: '404.040.414-69', parentesco: 'Mãe', telefone: '(82) 98712-3496', email: 'olga.drummond@email.com' },
    resp2: { nome: 'Frederico Pacheco Drummond', cpf: '505.050.515-79', parentesco: 'Pai', telefone: '(82) 98712-3497', email: 'frederico.pacheco@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Participante do grupo de primeiros socorros.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Igor Cavalcanti Vasconcelos',
    cpf: '707.717.727-15',
    rg: '7077177',
    nascimento: '2005-10-10',
    sexo: 'Masculino',
    email: 'igor.cavalcanti.vasc@email.com',
    telefone: '(82) 98712-3498',
    endereco: { rua: 'Rua Marquês de Herval', numero: '350', bairro: 'Centro', cidade: 'Maceió', estado: 'AL', cep: '57020-100', complemento: '' },
    matricula: 'TEC2024017',
    curso: 'Técnico em Segurança do Trabalho',
    modalidade: 'Técnico',
    polo: 'Sede',
    turma: 'SEG-D',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Joselita Vasconcelos Cavalcanti', cpf: '606.060.616-89', parentesco: 'Mãe', telefone: '(82) 98712-3499', email: 'joselita.vasc@email.com' },
    resp2: { nome: 'Orivaldo Cavalcanti Vasconcelos', cpf: '707.070.717-99', parentesco: 'Pai', telefone: '(82) 98712-3500', email: 'orivaldo.cav@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Centro/Mercado',
    obs_academica: 'Monitora condições de segurança no laboratório.',
    obs_administrativa: 'Documentação completa.',
  },

  // ── MODALIDADE: Itinerante (16) | POLO: Sede (5), Rio Branco (5), Flora Calheiros (6) ──
  {
    nome: 'Julia Meirelles Bastos',
    cpf: '808.818.828-26',
    rg: '8088188',
    nascimento: '2003-02-14',
    sexo: 'Feminino',
    email: 'julia.meirelles.bastos@email.com',
    telefone: '(82) 98712-3501',
    endereco: { rua: 'Rua Epitácio Pessoa', numero: '440', bairro: 'Ponta Grossa', cidade: 'Maceió', estado: 'AL', cep: '57017-200', complemento: '' },
    matricula: 'ITI2024001',
    curso: 'Técnico em Logística',
    modalidade: 'Itinerante',
    polo: 'Sede',
    turma: 'LOG-D',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Elisa Bastos Meirelles', cpf: '808.080.818-09', parentesco: 'Mãe', telefone: '(82) 98712-3502', email: 'elisa.bastos@email.com' },
    resp2: { nome: 'Claudio Meirelles Bastos', cpf: '909.090.919-19', parentesco: 'Pai', telefone: '(82) 98712-3503', email: 'claudio.meirelles@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Excelente participação nas aulas itinerantes.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Kleber Romualdo Peixoto',
    cpf: '909.919.929-37',
    rg: '9099199',
    nascimento: '2004-11-02',
    sexo: 'Masculino',
    email: 'kleber.romualdo.peixoto@email.com',
    telefone: '(82) 98712-3504',
    endereco: { rua: 'Av. Álvaro Otacílio', numero: '2200', bairro: 'Ponta Verde', cidade: 'Maceió', estado: 'AL', cep: '57035-200', complemento: 'Conj. 3' },
    matricula: 'ITI2024002',
    curso: 'Técnico em Eletrotécnica',
    modalidade: 'Itinerante',
    polo: 'Sede',
    turma: 'ELET-D',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Suely Peixoto Romualdo', cpf: '010.100.110-29', parentesco: 'Mãe', telefone: '(82) 98712-3505', email: 'suely.peixoto@email.com' },
    resp2: { nome: 'Marcos Romualdo Peixoto', cpf: '121.110.120-39', parentesco: 'Pai', telefone: '(82) 98712-3506', email: 'marcos.romualdo@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Realiza manutenção elétrica em residências como extra.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Luciana Fonseca Tavares',
    cpf: '010.020.030-48',
    rg: '0100200',
    nascimento: '2001-07-19',
    sexo: 'Feminino',
    email: 'luciana.fonseca.tavares@email.com',
    telefone: '(82) 98712-3507',
    endereco: { rua: 'Rua Governador Luiz Cavalcante', numero: '33', bairro: 'Tabuleiro do Pinto', cidade: 'Maceió', estado: 'AL', cep: '57084-000', complemento: '' },
    matricula: 'ITI2024003',
    curso: 'Técnico em Contabilidade',
    modalidade: 'Itinerante',
    polo: 'Sede',
    turma: 'CONT-D',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Em análise',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Marina Tavares Fonseca', cpf: '232.220.230-59', parentesco: 'Mãe', telefone: '(82) 98712-3508', email: 'marina.tavares@email.com' },
    resp2: { nome: 'Nivaldo Fonseca Tavares', cpf: '343.330.340-69', parentesco: 'Pai', telefone: '(82) 98712-3509', email: 'nivaldo.fonseca@email.com' },
    necessidade_especial: 'Baixa visão — necessita material ampliado',
    transporte: 'Utiliza transporte escolar — linha Tabuleiro/Centro',
    obs_academica: 'Material didático adaptado com fonte ampliada entregue.',
    obs_administrativa: 'Laudo oftalmológico arquivado.',
  },
  {
    nome: 'Marcelo Dias Novaes',
    cpf: '120.130.140-59',
    rg: '1201301',
    nascimento: '2005-04-06',
    sexo: 'Masculino',
    email: 'marcelo.dias.novaes@email.com',
    telefone: '(82) 98712-3510',
    endereco: { rua: 'Rua Maceió', numero: '500', bairro: 'Centro', cidade: 'Marechal Deodoro', estado: 'AL', cep: '57160-000', complemento: '' },
    matricula: 'ITI2024004',
    curso: 'Técnico em Agropecuária',
    modalidade: 'Itinerante',
    polo: 'Sede',
    turma: 'AGRO-D',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Em transferência',
    resp1: { nome: 'Neide Novaes Dias', cpf: '454.440.450-79', parentesco: 'Mãe', telefone: '(82) 98712-3511', email: 'neide.novaes@email.com' },
    resp2: { nome: 'Ronaldo Dias Novaes', cpf: '565.550.560-89', parentesco: 'Pai', telefone: '(82) 98712-3512', email: 'ronaldo.dias.n@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Marechal Deodoro/Sede',
    obs_academica: 'Transferência interna aprovada para outra turma.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Natalia Prado Sepúlveda',
    cpf: '230.240.250-60',
    rg: '2302402',
    nascimento: '2006-09-13',
    sexo: 'Feminino',
    email: 'natalia.prado.sepulveda@email.com',
    telefone: '(82) 98712-3513',
    endereco: { rua: 'Rua Coronel Bilhar', numero: '66', bairro: 'Centro', cidade: 'Marechal Deodoro', estado: 'AL', cep: '57160-010', complemento: 'Apto 3' },
    matricula: 'ITI2024005',
    curso: 'Técnico em Recursos Humanos',
    modalidade: 'Itinerante',
    polo: 'Sede',
    turma: 'RH-D',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Pendente de documentação',
    situacao_academica: 'Aguardando documentação',
    resp1: { nome: 'Eunice Sepúlveda Prado', cpf: '676.660.670-99', parentesco: 'Mãe', telefone: '(82) 98712-3514', email: 'eunice.sepulveda@email.com' },
    resp2: { nome: 'Tarcísio Prado Sepúlveda', cpf: '787.770.780-09', parentesco: 'Pai', telefone: '(82) 98712-3515', email: 'tarcisio.prado@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Aguardando documentos de série anterior.',
    obs_administrativa: 'Prazo para entrega: 30 dias.',
  },
  {
    nome: 'Orlando Luz Medeiros',
    cpf: '340.350.360-71',
    rg: '3403503',
    nascimento: '2003-12-26',
    sexo: 'Masculino',
    email: 'orlando.luz.medeiros@email.com',
    telefone: '(68) 98712-3516',
    endereco: { rua: 'Rua Santa Inês', numero: '190', bairro: 'Bosque', cidade: 'Rio Branco', estado: 'AC', cep: '69900-700', complemento: '' },
    matricula: 'ITI2024006',
    curso: 'Técnico em Informática',
    modalidade: 'Itinerante',
    polo: 'Rio Branco',
    turma: 'INF-E',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Conceição Medeiros Luz', cpf: '898.880.890-19', parentesco: 'Mãe', telefone: '(68) 98712-3517', email: 'conceicao.medeiros@email.com' },
    resp2: { nome: 'Adão Luz Medeiros', cpf: '909.990.990-29', parentesco: 'Pai', telefone: '(68) 98712-3518', email: 'adao.luz.med@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Desenvolveu app para controle de estoque do comércio local.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Priscila Aguiar Paiva',
    cpf: '450.460.470-82',
    rg: '4504604',
    nascimento: '2004-03-31',
    sexo: 'Feminino',
    email: 'priscila.aguiar.paiva@email.com',
    telefone: '(68) 98712-3519',
    endereco: { rua: 'Rua General Osório', numero: '78', bairro: 'Calafate', cidade: 'Rio Branco', estado: 'AC', cep: '69900-800', complemento: 'Casa 2' },
    matricula: 'ITI2024007',
    curso: 'Técnico em Administração',
    modalidade: 'Itinerante',
    polo: 'Rio Branco',
    turma: 'ADM-F',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Marta Paiva Aguiar', cpf: '010.011.012-39', parentesco: 'Mãe', telefone: '(68) 98712-3520', email: 'marta.paiva@email.com' },
    resp2: { nome: 'Welington Aguiar Paiva', cpf: '020.021.022-49', parentesco: 'Pai', telefone: '(68) 98712-3521', email: 'welington.aguiar@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Calafate/Centro',
    obs_academica: 'Ótima organização e pontualidade.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Quincy Batista Aragão',
    cpf: '560.570.580-93',
    rg: '5605705',
    nascimento: '2002-08-08',
    sexo: 'Masculino',
    email: 'quincy.batista.aragao@email.com',
    telefone: '(68) 98712-3522',
    endereco: { rua: 'Rua Rio Grande do Norte', numero: '300', bairro: 'Montanhês', cidade: 'Rio Branco', estado: 'AC', cep: '69900-900', complemento: '' },
    matricula: 'ITI2024008',
    curso: 'Técnico em Enfermagem',
    modalidade: 'Itinerante',
    polo: 'Rio Branco',
    turma: 'ENF-E',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Concluinte',
    resp1: { nome: 'Berenice Aragão Batista', cpf: '030.031.032-59', parentesco: 'Mãe', telefone: '(68) 98712-3523', email: 'berenice.aragao@email.com' },
    resp2: { nome: 'Estevão Batista Aragão', cpf: '040.041.042-69', parentesco: 'Pai', telefone: '(68) 98712-3524', email: 'estevao.batista@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Finaliza o curso com 95% de aproveitamento.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Rita de Cássia Amorim Gadelha',
    cpf: '670.680.690-04',
    rg: '6706806',
    nascimento: '2005-05-05',
    sexo: 'Feminino',
    email: 'rita.amorim.gadelha@email.com',
    telefone: '(68) 98712-3525',
    endereco: { rua: 'Rua Amazonas', numero: '67', bairro: 'Seis de Agosto', cidade: 'Rio Branco', estado: 'AC', cep: '69901-000', complemento: 'Apto 101' },
    matricula: 'ITI2024009',
    curso: 'Técnico em Segurança do Trabalho',
    modalidade: 'Itinerante',
    polo: 'Rio Branco',
    turma: 'SEG-E',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Indeferido',
    situacao_academica: 'Em regularização',
    resp1: { nome: 'Zilda Gadelha Amorim', cpf: '050.051.052-79', parentesco: 'Mãe', telefone: '(68) 98712-3526', email: 'zilda.gadelha@email.com' },
    resp2: { nome: 'Atanásio Amorim Gadelha', cpf: '060.061.062-89', parentesco: 'Pai', telefone: '(68) 98712-3527', email: 'atanasio.amorim@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Processo indeferido; nova documentação entregue para reanálise.',
    obs_administrativa: 'Em regularização desde o último semestre.',
  },
  {
    nome: 'Silas Mendonça Rios',
    cpf: '780.790.800-15',
    rg: '7807908',
    nascimento: '2003-10-22',
    sexo: 'Masculino',
    email: 'silas.mendonca.rios@email.com',
    telefone: '(68) 98712-3528',
    endereco: { rua: 'Av. Ceará', numero: '1800', bairro: 'Universitário', cidade: 'Rio Branco', estado: 'AC', cep: '69920-000', complemento: '' },
    matricula: 'ITI2024010',
    curso: 'Técnico em Logística',
    modalidade: 'Itinerante',
    polo: 'Rio Branco',
    turma: 'LOG-E',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Aguardando matrícula',
    situacao_academica: 'Trancado',
    resp1: { nome: 'Vera Rios Mendonça', cpf: '070.071.072-99', parentesco: 'Mãe', telefone: '(68) 98712-3529', email: 'vera.rios@email.com' },
    resp2: { nome: 'Firmino Mendonça Rios', cpf: '080.081.082-09', parentesco: 'Pai', telefone: '(68) 98712-3530', email: 'firmino.mendonca@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Universitário/Centro',
    obs_academica: 'Solicitou trancamento por motivos de saúde.',
    obs_administrativa: 'Atestado médico arquivado.',
  },
  {
    nome: 'Talita Vianna Azambuja',
    cpf: '890.900.910-26',
    rg: '8909009',
    nascimento: '2004-07-15',
    sexo: 'Feminino',
    email: 'talita.vianna.azambuja@email.com',
    telefone: '(82) 98712-3531',
    endereco: { rua: 'Rua Padre Cícero', numero: '111', bairro: 'Bebedouro', cidade: 'Maceió', estado: 'AL', cep: '57025-700', complemento: '' },
    matricula: 'ITI2024011',
    curso: 'Técnico em Contabilidade',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'CONT-E',
    turno: 'Noite',
    ano_semestre: '2024/2',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Denise Azambuja Vianna', cpf: '090.091.092-19', parentesco: 'Mãe', telefone: '(82) 98712-3532', email: 'denise.azambuja@email.com' },
    resp2: { nome: 'Lauro Vianna Azambuja', cpf: '001.002.003-29', parentesco: 'Pai', telefone: '(82) 98712-3533', email: 'lauro.vianna@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Não utiliza',
    obs_academica: 'Auxiliar contábil em empresa familiar.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Umberto Sales Viana',
    cpf: '910.920.930-37',
    rg: '9109209',
    nascimento: '2002-01-25',
    sexo: 'Masculino',
    email: 'umberto.sales.viana@email.com',
    telefone: '(82) 98712-3534',
    endereco: { rua: 'Rua Santa Clara', numero: '202', bairro: 'Centro', cidade: 'São Miguel dos Campos', estado: 'AL', cep: '57240-000', complemento: '' },
    matricula: 'ITI2024012',
    curso: 'Técnico em Eletrotécnica',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'ELET-E',
    turno: 'Manhã',
    ano_semestre: '2024/1',
    status_processo: 'Aprovado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Célia Viana Sales', cpf: '002.003.004-39', parentesco: 'Mãe', telefone: '(82) 98712-3535', email: 'celia.viana@email.com' },
    resp2: { nome: 'Adalberto Sales Viana', cpf: '003.004.005-49', parentesco: 'Pai', telefone: '(82) 98712-3536', email: 'adalberto.sales@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha São Miguel/Sede',
    obs_academica: 'Responsável pela manutenção elétrica da escola parceira.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Viviane Mota Furtado',
    cpf: '020.030.040-48',
    rg: '0200300',
    nascimento: '2005-06-06',
    sexo: 'Feminino',
    email: 'viviane.mota.furtado@email.com',
    telefone: '(82) 98712-3537',
    endereco: { rua: 'Rua Independência', numero: '303', bairro: 'Vila Progresso', cidade: 'São Miguel dos Campos', estado: 'AL', cep: '57240-010', complemento: 'Casa 4' },
    matricula: 'ITI2024013',
    curso: 'Técnico em Agropecuária',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'AGRO-E',
    turno: 'Tarde',
    ano_semestre: '2024/2',
    status_processo: 'Em análise',
    situacao_academica: 'Matriculado',
    resp1: { nome: 'Irene Furtado Mota', cpf: '004.005.006-59', parentesco: 'Mãe', telefone: '(82) 98712-3538', email: 'irene.furtado@email.com' },
    resp2: { nome: 'Osvaldo Mota Furtado', cpf: '005.006.007-69', parentesco: 'Pai', telefone: '(82) 98712-3539', email: 'osvaldo.mota@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha São Miguel/Sede',
    obs_academica: 'Trabalha em propriedade rural nos finais de semana.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Wilson Rocha Leandro',
    cpf: '130.140.150-59',
    rg: '1301401',
    nascimento: '2003-03-14',
    sexo: 'Masculino',
    email: 'wilson.rocha.leandro@email.com',
    telefone: '(82) 98712-3540',
    endereco: { rua: 'Rua Bela Vista', numero: '404', bairro: 'Centro', cidade: 'Penedo', estado: 'AL', cep: '57200-000', complemento: '' },
    matricula: 'ITI2024014',
    curso: 'Técnico em Meio Ambiente',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'MEIO-D',
    turno: 'Noite',
    ano_semestre: '2024/1',
    status_processo: 'Matriculado',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Lúcia Leandro Rocha', cpf: '006.007.008-79', parentesco: 'Mãe', telefone: '(82) 98712-3541', email: 'lucia.leandro@email.com' },
    resp2: { nome: 'Everton Rocha Leandro', cpf: '007.008.009-89', parentesco: 'Pai', telefone: '(82) 98712-3542', email: 'everton.rocha.l@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Penedo/Sede',
    obs_academica: 'Pesquisador do projeto de recuperação do Rio São Francisco.',
    obs_administrativa: 'Documentação completa.',
  },
  {
    nome: 'Yasmin Corrêa Pinheiro',
    cpf: '240.250.260-60',
    rg: '2402502',
    nascimento: '2006-11-20',
    sexo: 'Feminino',
    email: 'yasmin.correa.pinheiro@email.com',
    telefone: '(82) 98712-3543',
    endereco: { rua: 'Av. Barão de Penedo', numero: '55', bairro: 'São Gonçalo do Amarante', cidade: 'Penedo', estado: 'AL', cep: '57200-100', complemento: '' },
    matricula: 'ITI2024015',
    curso: 'Técnico em Informática',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'INF-F',
    turno: 'Manhã',
    ano_semestre: '2024/2',
    status_processo: 'Pendente de documentação',
    situacao_academica: 'Aguardando documentação',
    resp1: { nome: 'Josilene Pinheiro Corrêa', cpf: '008.009.010-99', parentesco: 'Mãe', telefone: '(82) 98712-3544', email: 'josilene.pinheiro@email.com' },
    resp2: { nome: 'Ailton Corrêa Pinheiro', cpf: '009.010.011-09', parentesco: 'Pai', telefone: '(82) 98712-3545', email: 'ailton.correa@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Penedo/Sede',
    obs_academica: 'Interesse em desenvolvimento mobile.',
    obs_administrativa: 'Pendente histórico escolar.',
  },
  {
    nome: 'Zélio Camargo Torres',
    cpf: '350.360.370-71',
    rg: '3503603',
    nascimento: '2004-08-29',
    sexo: 'Masculino',
    email: 'zelio.camargo.torres@email.com',
    telefone: '(82) 98712-3546',
    endereco: { rua: 'Rua Bom Jesus', numero: '606', bairro: 'Boa Vista', cidade: 'Penedo', estado: 'AL', cep: '57200-200', complemento: 'Apto 2' },
    matricula: 'ITI2024016',
    curso: 'Técnico em Administração',
    modalidade: 'Itinerante',
    polo: 'Flora Calheiros',
    turma: 'ADM-G',
    turno: 'Tarde',
    ano_semestre: '2024/1',
    status_processo: 'Em acompanhamento',
    situacao_academica: 'Ativo',
    resp1: { nome: 'Aurea Torres Camargo', cpf: '010.011.012-19', parentesco: 'Mãe', telefone: '(82) 98712-3547', email: 'aurea.torres@email.com' },
    resp2: { nome: 'Benedito Camargo Torres', cpf: '011.012.013-29', parentesco: 'Pai', telefone: '(82) 98712-3548', email: 'benedito.camargo@email.com' },
    necessidade_especial: 'Não possui',
    transporte: 'Utiliza transporte escolar — linha Penedo/Sede',
    obs_academica: 'Empreendedor local — vende produtos artesanais.',
    obs_administrativa: 'Documentação completa.',
  },
];

// ─── Funções auxiliares ───────────────────────────────────────────────────────

function calcularIdade(nascimento) {
  const hoje = new Date();
  const nasc = new Date(nascimento);
  let idade = hoje.getFullYear() - nasc.getFullYear();
  if (hoje < new Date(hoje.getFullYear(), nasc.getMonth(), nasc.getDate())) idade--;
  return idade;
}

async function preencherCampo(page, seletor, valor, tentativas = 3) {
  for (let t = 0; t < tentativas; t++) {
    try {
      const el = await page.$(seletor);
      if (el) {
        await el.click({ force: true });
        await el.fill('');
        await el.type(valor, { delay: 30 });
        return true;
      }
    } catch (_) {}
    await page.waitForTimeout(300);
  }
  return false;
}

async function selecionarOpcao(page, seletor, valor) {
  try {
    const el = await page.$(seletor);
    if (!el) return false;
    await el.selectOption(valor).catch(async () => {
      // tenta por texto
      const opts = await el.$$('option');
      for (const opt of opts) {
        const txt = await opt.innerText();
        if (txt.toLowerCase().includes(valor.toLowerCase())) {
          const val = await opt.getAttribute('value');
          await el.selectOption(val);
          return;
        }
      }
    });
    return true;
  } catch (_) { return false; }
}

async function clicarBotao(page, textos) {
  for (const texto of textos) {
    try {
      const btn = await page.locator(`button:has-text("${texto}")`).first();
      if (await btn.isVisible()) { await btn.click(); return true; }
    } catch (_) {}
    try {
      const btn = await page.locator(`[value="${texto}"]`).first();
      if (await btn.isVisible()) { await btn.click(); return true; }
    } catch (_) {}
  }
  return false;
}

async function tirarScreenshot(page, nome) {
  await page.screenshot({ path: `scripts/screenshots/${nome}.png`, fullPage: false });
}

// ─── Detectar estrutura do formulário ────────────────────────────────────────

async function detectarEstrutura(page) {
  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});

  const estrutura = await page.evaluate(() => {
    const inputs = Array.from(document.querySelectorAll('input, select, textarea'));
    const buttons = Array.from(document.querySelectorAll('button, [type="submit"]'));
    const forms = Array.from(document.querySelectorAll('form'));
    const tabs = Array.from(document.querySelectorAll('[role="tab"], .tab, .nav-tab, .tab-link'));

    return {
      inputs: inputs.slice(0, 50).map(i => ({
        tag: i.tagName,
        type: i.type || '',
        name: i.name || '',
        id: i.id || '',
        placeholder: i.placeholder || '',
        label: i.labels?.[0]?.innerText || '',
        classes: i.className,
      })),
      buttons: buttons.slice(0, 20).map(b => ({
        text: b.innerText?.trim() || b.value || '',
        type: b.type || '',
        id: b.id || '',
        classes: b.className,
      })),
      formsCount: forms.length,
      tabsCount: tabs.length,
      tabs: tabs.map(t => t.innerText?.trim() || ''),
    };
  });

  return estrutura;
}

// ─── Cadastro de um aluno ─────────────────────────────────────────────────────

async function cadastrarAluno(page, aluno, index) {
  console.log(`\n[${index + 1}/50] Cadastrando: ${aluno.nome}`);

  // Navegar para /processos e abrir novo cadastro
  await page.goto('http://10.255.27.252:5175/processos', { waitUntil: 'domcontentloaded', timeout: 30000 });
  await page.waitForTimeout(1500);

  // Detectar estrutura na primeira iteração
  if (index === 0) {
    const estrutura = await detectarEstrutura(page);
    console.log('Estrutura detectada:', JSON.stringify(estrutura, null, 2));
    require('fs').writeFileSync('scripts/estrutura_detectada.json', JSON.stringify(estrutura, null, 2));
  }

  // Tentar clicar em botão de novo cadastro
  const botaoNovoCadastro = await clicarBotao(page, [
    'Novo', 'Novo Processo', 'Novo Aluno', 'Cadastrar', 'Adicionar',
    'New', 'Criar', 'Nova Matrícula', '+', 'Iniciar Processo',
  ]);

  if (!botaoNovoCadastro) {
    // Tentar link com href
    const link = await page.$('a[href*="novo"], a[href*="new"], a[href*="criar"], a[href*="add"]');
    if (link) await link.click();
    else {
      console.warn('  Botão de novo cadastro não encontrado. Tentando URL direta...');
      await page.goto('http://10.255.27.252:5175/processos/novo', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(async () => {
        await page.goto('http://10.255.27.252:5175/processos/new', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {});
      });
    }
  }

  await page.waitForTimeout(2000);
  await tirarScreenshot(page, `aluno_${index + 1}_formulario`);

  // ── Preencher campos por estratégia genérica ──────────────────────────────

  const idade = calcularIdade(aluno.nascimento);

  // Mapa de campos: [array de seletores possíveis] -> valor
  const mapeamento = [
    { seletores: ['[name="nome"]', '[placeholder*="ome"]', '#nome', 'input[id*="nome"]'], valor: aluno.nome },
    { seletores: ['[name="cpf"]', '[placeholder*="CPF"]', '#cpf', 'input[id*="cpf"]'], valor: aluno.cpf },
    { seletores: ['[name="rg"]', '[placeholder*="RG"]', '#rg', 'input[id*="rg"]'], valor: aluno.rg },
    { seletores: ['[name*="nascimento"]', '[name*="data_nasc"]', '[placeholder*="nascimento"]', '#data_nascimento'], valor: aluno.nascimento },
    { seletores: ['[name="idade"]', '[placeholder*="dade"]', '#idade'], valor: String(idade) },
    { seletores: ['[name="email"]', '[placeholder*="mail"]', '#email', 'input[type="email"]'], valor: aluno.email },
    { seletores: ['[name="telefone"]', '[name="celular"]', '[placeholder*="elefone"]', '#telefone'], valor: aluno.telefone },
    { seletores: ['[name*="matricula"]', '[placeholder*="atrícula"]', '#matricula'], valor: aluno.matricula },
    { seletores: ['[name="rua"]', '[name*="endereco"]', '[name*="logradouro"]', '[placeholder*="ua"]'], valor: aluno.endereco.rua },
    { seletores: ['[name="numero"]', '[placeholder*="úmero"]', '#numero'], valor: aluno.endereco.numero },
    { seletores: ['[name="bairro"]', '[placeholder*="airro"]', '#bairro'], valor: aluno.endereco.bairro },
    { seletores: ['[name="cidade"]', '[placeholder*="idade"]', '#cidade'], valor: aluno.endereco.cidade },
    { seletores: ['[name="estado"]', '[name="uf"]', '[placeholder*="stado"]', '#estado', '#uf'], valor: aluno.endereco.estado },
    { seletores: ['[name="cep"]', '[placeholder*="CEP"]', '#cep'], valor: aluno.endereco.cep },
    { seletores: ['[name="complemento"]', '[placeholder*="omplemento"]', '#complemento'], valor: aluno.endereco.complemento },
    { seletores: ['[name*="turma"]', '[placeholder*="urma"]', '#turma'], valor: aluno.turma },
    { seletores: ['[name*="ano"]', '[name*="semestre"]', '[placeholder*="no"]', '#ano_semestre'], valor: aluno.ano_semestre },
    { seletores: ['[name*="obs_acad"]', '[name*="observacao_acad"]', '[placeholder*="cadêm"]', '#obs_academica'], valor: aluno.obs_academica },
    { seletores: ['[name*="obs_adm"]', '[name*="observacao_adm"]', '[placeholder*="dmin"]', '#obs_administrativa'], valor: aluno.obs_administrativa },
    { seletores: ['[name*="necessidade"]', '[placeholder*="ecessidade"]', '#necessidade_especial'], valor: aluno.necessidade_especial },
    { seletores: ['[name*="transporte"]', '[placeholder*="ransporte"]', '#transporte'], valor: aluno.transporte },
    // Responsável 1
    { seletores: ['[name*="resp1_nome"]', '[name*="responsavel1_nome"]', '[placeholder*="esponsável 1"]', '#resp1_nome'], valor: aluno.resp1.nome },
    { seletores: ['[name*="resp1_cpf"]', '[name*="responsavel1_cpf"]', '#resp1_cpf'], valor: aluno.resp1.cpf },
    { seletores: ['[name*="resp1_parentesco"]', '[name*="responsavel1_parentesco"]', '#resp1_parentesco'], valor: aluno.resp1.parentesco },
    { seletores: ['[name*="resp1_tel"]', '[name*="responsavel1_tel"]', '#resp1_telefone'], valor: aluno.resp1.telefone },
    { seletores: ['[name*="resp1_email"]', '[name*="responsavel1_email"]', '#resp1_email'], valor: aluno.resp1.email },
    // Responsável 2
    { seletores: ['[name*="resp2_nome"]', '[name*="responsavel2_nome"]', '#resp2_nome'], valor: aluno.resp2.nome },
    { seletores: ['[name*="resp2_cpf"]', '[name*="responsavel2_cpf"]', '#resp2_cpf'], valor: aluno.resp2.cpf },
    { seletores: ['[name*="resp2_parentesco"]', '[name*="responsavel2_parentesco"]', '#resp2_parentesco'], valor: aluno.resp2.parentesco },
    { seletores: ['[name*="resp2_tel"]', '[name*="responsavel2_tel"]', '#resp2_telefone'], valor: aluno.resp2.telefone },
    { seletores: ['[name*="resp2_email"]', '[name*="responsavel2_email"]', '#resp2_email'], valor: aluno.resp2.email },
  ];

  for (const campo of mapeamento) {
    for (const sel of campo.seletores) {
      const ok = await preencherCampo(page, sel, campo.valor);
      if (ok) break;
    }
  }

  // Selects (dropdowns)
  const selects = [
    { seletores: ['[name="sexo"]', '#sexo', 'select[id*="sexo"]'], valor: aluno.sexo },
    { seletores: ['[name="modalidade"]', '#modalidade', 'select[id*="modalidade"]'], valor: aluno.modalidade },
    { seletores: ['[name="polo"]', '#polo', 'select[id*="polo"]'], valor: aluno.polo },
    { seletores: ['[name*="curso"]', '#curso', 'select[id*="curso"]'], valor: aluno.curso },
    { seletores: ['[name="turno"]', '#turno', 'select[id*="turno"]'], valor: aluno.turno },
    { seletores: ['[name*="status"]', '#status_processo', 'select[id*="status"]'], valor: aluno.status_processo },
    { seletores: ['[name*="situacao"]', '#situacao_academica', 'select[id*="situacao"]'], valor: aluno.situacao_academica },
  ];

  for (const campo of selects) {
    for (const sel of campo.seletores) {
      const ok = await selecionarOpcao(page, sel, campo.valor);
      if (ok) break;
    }
  }

  // Tenta salvar
  await clicarBotao(page, ['Salvar', 'Gravar', 'Confirmar', 'Cadastrar', 'Enviar', 'Submit', 'Próximo', 'Avançar']);
  await page.waitForTimeout(2000);
  await tirarScreenshot(page, `aluno_${index + 1}_salvo`);

  console.log(`  ✓ ${aluno.nome} processado`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

(async () => {
  require('fs').mkdirSync('scripts/screenshots', { recursive: true });

  const browser = await chromium.launch({
    headless: false, // visível para acompanhamento
    slowMo: 50,
  });

  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
  });

  const page = await context.newPage();

  // Acessar o sistema pela primeira vez
  console.log('Acessando o sistema...');
  await page.goto('http://10.255.27.252:5175/processos', { waitUntil: 'domcontentloaded', timeout: 30000 });
  await page.waitForTimeout(2000);

  // Screenshot inicial
  await tirarScreenshot(page, '00_pagina_inicial');

  // Detectar estrutura antes de começar
  const estrutura = await detectarEstrutura(page);
  console.log('\n=== Estrutura da página ===');
  console.log('Inputs encontrados:', estrutura.inputs.length);
  console.log('Botões:', estrutura.buttons.map(b => b.text).join(', '));
  console.log('Abas:', estrutura.tabs.join(', '));
  require('fs').writeFileSync('scripts/estrutura_detectada.json', JSON.stringify(estrutura, null, 2));

  console.log('\nIniciando cadastro de 50 alunos...\n');

  let sucessos = 0;
  let falhas = [];

  for (let i = 0; i < ALUNOS.length; i++) {
    try {
      await cadastrarAluno(page, ALUNOS[i], i);
      sucessos++;
    } catch (err) {
      console.error(`  ✗ ERRO ao cadastrar ${ALUNOS[i].nome}: ${err.message}`);
      falhas.push({ index: i + 1, nome: ALUNOS[i].nome, erro: err.message });
      await tirarScreenshot(page, `aluno_${i + 1}_erro`);
    }
  }

  console.log(`\n=== RESULTADO FINAL ===`);
  console.log(`✓ Cadastros realizados: ${sucessos}/50`);
  if (falhas.length > 0) {
    console.log(`✗ Falhas (${falhas.length}):`);
    falhas.forEach(f => console.log(`  - Aluno ${f.index} (${f.nome}): ${f.erro}`));
  }

  require('fs').writeFileSync('scripts/resultado_cadastro.json', JSON.stringify({ sucessos, falhas }, null, 2));

  await page.waitForTimeout(3000);
  await browser.close();
})();
