# Generated by Django 6.0.3 on 2026-03-23 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_ataoficiomemorando_ano_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEscolarDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PARCIAL', 'DocumentoHistoricoEscolarParcial'), ('FINAL', 'DocumentoHistoricoEscolarFinal'), ('SEGUNDA_VIA_NATO_FISICO', 'DocumentoHistoricoEscolarSegundaViaNatoFisico')], max_length=32, verbose_name='Tipo do Documento MEC')),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('VALIDADO', 'Validado'), ('ASSINADO', 'Assinado'), ('REVOGADO', 'Revogado'), ('ERRO', 'Erro')], default='GERADO', max_length=16, verbose_name='Status')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versao')),
                ('numero_unico', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Numero Unico')),
                ('hash_documento', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('chave_autenticacao', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Chave de Autenticacao')),
                ('xml_conteudo', models.TextField(verbose_name='XML Gerado')),
                ('xml_assinado_conteudo', models.TextField(blank=True, verbose_name='XML Assinado')),
                ('validacao_xsd_ok', models.BooleanField(default=False, verbose_name='Validacao XSD OK')),
                ('validacao_xsd_erros', models.JSONField(blank=True, default=list, verbose_name='Erros da Validacao XSD')),
                ('assinado_digitalmente', models.BooleanField(default=False, verbose_name='Assinado Digitalmente')),
                ('assinatura_metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados de Assinatura')),
                ('qr_payload_url', models.CharField(blank=True, max_length=600, verbose_name='URL de Validacao por QR Code')),
                ('qr_code_data_uri', models.TextField(blank=True, verbose_name='QR Code Data URI')),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='documentos/historicos_digitais/pdf/', verbose_name='PDF Institucional')),
                ('revogado', models.BooleanField(default=False, verbose_name='Revogado')),
                ('motivo_revogacao', models.TextField(blank=True, verbose_name='Motivo da Revogacao')),
                ('emitido_em', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_digitais_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes_digitais', to='documentos.historicoescolar', verbose_name='Historico Base')),
                ('referencia_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segundas_vias_emitidas', to='documentos.historicoescolardigital', verbose_name='Documento Digital Original')),
            ],
            options={
                'verbose_name': 'Historico Escolar Digital',
                'verbose_name_plural': 'Historicos Escolares Digitais',
                'ordering': ['-emitido_em', '-id'],
                'indexes': [models.Index(fields=['numero_unico'], name='documentos__numero__5fe52c_idx'), models.Index(fields=['chave_autenticacao'], name='documentos__chave_a_a59335_idx'), models.Index(fields=['tipo_documento', 'status'], name='documentos__tipo_do_933688_idx'), models.Index(fields=['historico', 'versao'], name='documentos__histori_353f3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('historico', 'versao'), name='uniq_historico_digital_versao_por_historico')],
            },
        ),
    ]
