# Generated by Django 6.0.3 on 2026-03-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_ofertacurso_template_sync_metadata'),
        ('documentos', '0003_historicoescolardigital'),
        ('unidades', '0003_merge_20260305_1203'),
        ('usuarios', '0008_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEscolarTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.05', max_length=10)),
                ('ambiente', models.CharField(default='Produção', max_length=20)),
                ('data_ingresso', models.DateField()),
                ('forma_acesso', models.CharField(default='Processo Seletivo', max_length=100)),
                ('data_emissao_historico', models.DateField()),
                ('hora_emissao_historico', models.TimeField()),
                ('carga_horaria_integralizada', models.PositiveIntegerField(default=0)),
                ('carga_horaria_curso', models.PositiveIntegerField(default=1200)),
                ('codigo_validacao', models.CharField(blank=True, max_length=60, unique=True)),
                ('informacoes_adicionais', models.TextField(blank=True)),
                ('data_conclusao_curso', models.DateField(blank=True, null=True)),
                ('data_colacao_grau', models.DateField(blank=True, null=True)),
                ('data_expedicao_diploma', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_tecnicos', to='usuarios.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tecnicos', to='cursos.curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tecnicos', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Historico Escolar Tecnico',
                'verbose_name_plural': 'Historicos Escolares Tecnicos',
                'ordering': ['-data_emissao_historico', '-id'],
                'indexes': [models.Index(fields=['codigo_validacao'], name='documentos__codigo__c1e0de_idx'), models.Index(fields=['aluno', 'curso'], name='documentos__aluno_i_b99199_idx'), models.Index(fields=['instituicao', 'data_emissao_historico'], name='documentos__institu_557077_idx')],
            },
        ),
    ]
