# Generated by Django 6.0.3 on 2026-04-01 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_ofertacurso_template_sync_metadata'),
        ('documentos', '0004_historicoescolartecnico'),
        ('matriculas', '0013_dependenciaacademica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(default='IDEP-ETEC/RO', max_length=200, verbose_name='Nome da Instituicao')),
                ('subtitulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Subtitulo')),
                ('livro_padrao', models.CharField(blank=True, default='1', max_length=30, verbose_name='Livro padrao')),
                ('folha_padrao', models.CharField(blank=True, default='1', max_length=30, verbose_name='Folha padrao')),
                ('pagina_padrao', models.CharField(blank=True, default='1', max_length=30, verbose_name='Pagina padrao')),
                ('carga_horaria_minima_aprovacao', models.PositiveIntegerField(default=0, verbose_name='CH minima')),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Nota minima')),
                ('frequencia_minima_aprovacao', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Frequencia minima')),
                ('assinatura_1_nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Assinatura 1 Nome')),
                ('assinatura_1_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Assinatura 1 Cargo')),
                ('assinatura_2_nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Assinatura 2 Nome')),
                ('assinatura_2_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Assinatura 2 Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de Historico',
                'verbose_name_plural': 'Configuracoes de Historico',
                'ordering': ['-ativo', '-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolarTecnicoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('numero_registro', models.CharField(max_length=40, unique=True, verbose_name='Numero de Registro')),
                ('livro', models.CharField(blank=True, default='', max_length=30, verbose_name='Livro')),
                ('folha', models.CharField(blank=True, default='', max_length=30, verbose_name='Folha')),
                ('pagina', models.CharField(blank=True, default='', max_length=30, verbose_name='Pagina')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versao')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido'), ('CANCELADO', 'Cancelado'), ('SUBSTITUIDO', 'Substituido')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('hash_documento', models.CharField(max_length=64, verbose_name='Hash do Documento')),
                ('codigo_validacao', models.CharField(max_length=32, unique=True, verbose_name='Codigo de Validacao')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Emissao')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo de Cancelamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes Academicas')),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='documentos/historicos_tecnicos/pdf/', verbose_name='PDF')),
                ('qrcode_imagem', models.ImageField(blank=True, null=True, upload_to='documentos/historicos_tecnicos/qrcode/', verbose_name='Imagem QR Code')),
                ('carga_horaria_total', models.PositiveIntegerField(default=0, verbose_name='Carga Horaria Total')),
                ('situacao_final', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM_ANDAMENTO', 'Em andamento'), ('TRANSFERIDO', 'Transferido'), ('INDEFINIDA', 'Indefinida')], default='INDEFINIDA', max_length=20, verbose_name='Situacao Final')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tecnicos_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tecnicos_documentos', to='cursos.curso', verbose_name='Curso')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_tecnicos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('historico_substituido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_substitutos', to='documentos.historicoescolartecnicodocumento', verbose_name='Historico Substituido')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_tecnicos_documentos', to='matriculas.matricula', verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Historico Escolar Tecnico (Documento)',
                'verbose_name_plural': 'Historicos Escolares Tecnicos (Documentos)',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_nome', models.CharField(max_length=220, verbose_name='Nome do Componente')),
                ('modulo_periodo', models.CharField(blank=True, default='', max_length=80, verbose_name='Modulo/Periodo/Serie')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horaria')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frequencia')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CURSANDO', 'Cursando'), ('APROVEITADO', 'Aproveitado'), ('DISPENSADO', 'Dispensado')], default='CURSANDO', max_length=20, verbose_name='Resultado')),
                ('ordem_exibicao', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibicao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('componente_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_itens', to='cursos.componentecurricular', verbose_name='Componente Curricular')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='documentos.historicoescolartecnicodocumento', verbose_name='Historico')),
            ],
            options={
                'verbose_name': 'Historico Escolar Item',
                'verbose_name_plural': 'Historico Escolar Itens',
                'ordering': ['ordem_exibicao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('EMISSAO', 'Emissao'), ('REEMISSAO', 'Reemissao'), ('CANCELAMENTO', 'Cancelamento'), ('VISUALIZACAO', 'Visualizacao'), ('VALIDACAO_PUBLICA', 'Validacao Publica')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historico_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='documentos.historicoescolartecnicodocumento', verbose_name='Historico')),
            ],
            options={
                'verbose_name': 'Historico Escolar Evento',
                'verbose_name_plural': 'Historico Escolar Eventos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_documento', models.CharField(max_length=64, verbose_name='Hash')),
                ('hash_resumido', models.CharField(max_length=16, verbose_name='Hash Resumido')),
                ('url_validacao', models.CharField(max_length=500, verbose_name='URL de Validacao')),
                ('valido', models.BooleanField(default=True, verbose_name='Valido')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('historico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacao', to='documentos.historicoescolartecnicodocumento', verbose_name='Historico')),
            ],
            options={
                'verbose_name': 'Documento Validacao',
                'verbose_name_plural': 'Documentos Validacao',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('identificador', models.CharField(blank=True, default='', max_length=60, verbose_name='Identificador')),
                ('assinatura_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash da Assinatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='documentos.historicoescolartecnicodocumento', verbose_name='Historico')),
            ],
            options={
                'verbose_name': 'Assinatura de Documento',
                'verbose_name_plural': 'Assinaturas de Documento',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='historicoescolartecnicodocumento',
            index=models.Index(fields=['uuid'], name='documentos__uuid_ca462a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolartecnicodocumento',
            index=models.Index(fields=['codigo_validacao'], name='documentos__codigo__b759fa_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolartecnicodocumento',
            index=models.Index(fields=['aluno', 'curso'], name='documentos__aluno_i_1ea30d_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolartecnicodocumento',
            index=models.Index(fields=['matricula', 'status'], name='documentos__matricu_b1ff99_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolaritem',
            index=models.Index(fields=['historico', 'ordem_exibicao'], name='documentos__histori_80328d_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolaritem',
            index=models.Index(fields=['resultado'], name='documentos__resulta_e651d3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolarevento',
            index=models.Index(fields=['historico', 'tipo_evento'], name='documentos__histori_84191a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoescolarevento',
            index=models.Index(fields=['criado_em'], name='documentos__criado__f0f072_idx'),
        ),
        migrations.AddIndex(
            model_name='documentovalidacao',
            index=models.Index(fields=['hash_documento'], name='documentos__hash_do_e00800_idx'),
        ),
        migrations.AddIndex(
            model_name='documentovalidacao',
            index=models.Index(fields=['hash_resumido'], name='documentos__hash_re_c73fdd_idx'),
        ),
    ]
