# Generated by Django 6.0.3 on 2026-03-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0006_add_transferencia_regra_consolidacao'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Registro')),
                ('tipo_documento', models.CharField(choices=[('PASTA_ALUNO', 'Pasta do Aluno'), ('PROCESSO', 'Processo Administrativo'), ('CONTRATO', 'Contrato'), ('ATA', 'Ata'), ('DECLARACAO', 'Declaração'), ('HISTORICO', 'Histórico Escolar'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('numero_caixa', models.CharField(blank=True, max_length=50, verbose_name='Nº da Caixa')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização (Prateleira/Sala)')),
                ('data_arquivamento', models.DateField(auto_now_add=True, verbose_name='Data de Arquivamento')),
                ('data_eliminacao_prevista', models.DateField(blank=True, null=True, verbose_name='Data de Eliminação Prevista')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EMPRESTADO', 'Emprestado'), ('ELIMINADO', 'Eliminado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardas_documentais', to='matriculas.matricula', verbose_name='Matrícula Vinculada')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardas_documentais', to='processos.processo', verbose_name='Processo Vinculado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardas_documentais', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Arquivamento')),
            ],
            options={
                'verbose_name': 'Guarda Documental',
                'verbose_name_plural': 'Guarda Documental',
                'ordering': ['-data_arquivamento'],
            },
        ),
        migrations.CreateModel(
            name='EmprestimoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='arquivo.guardadocumental')),
            ],
            options={
                'verbose_name': 'Empréstimo de Documento',
                'verbose_name_plural': 'Empréstimos de Documentos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
