# Generated by Django 6.0.3 on 2026-03-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_atual', models.CharField(choices=[('CLASSIFICADO', 'Classificar Documento'), ('INDEXADO', 'Indexar / Localizar'), ('PRAZO_APLICADO', 'Aplicar Prazo de Guarda'), ('ELIMINADO', 'Eliminar + Termo')], default='CLASSIFICADO', max_length=20, verbose_name='Etapa Atual')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_arquivo', to='arquivo.guardadocumental', verbose_name='Guarda Documental')),
            ],
            options={
                'verbose_name': 'Fluxo de Arquivo',
                'verbose_name_plural': 'Fluxos de Arquivo',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('CLASSIFICADO', 'Classificar Documento'), ('INDEXADO', 'Indexar / Localizar'), ('PRAZO_APLICADO', 'Aplicar Prazo de Guarda'), ('ELIMINADO', 'Eliminar + Termo')], max_length=20, verbose_name='Etapa')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_fluxo_arquivo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_etapas', to='arquivo.fluxoarquivo')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo de Arquivo',
                'verbose_name_plural': 'Etapas do Fluxo de Arquivo',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='TermoEliminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº do Termo')),
                ('data_termo', models.DateField(auto_now_add=True, verbose_name='Data do Termo')),
                ('justificativa', models.TextField(verbose_name='Justificativa de Eliminação')),
                ('data_autorizacao', models.DateField(blank=True, null=True, verbose_name='Data de Autorização')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_eliminacao', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('fluxo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo_eliminacao', to='arquivo.fluxoarquivo', verbose_name='Fluxo de Arquivo')),
            ],
            options={
                'verbose_name': 'Termo de Eliminação',
                'verbose_name_plural': 'Termos de Eliminação',
                'ordering': ['-data_termo'],
            },
        ),
    ]
