# Generated by Django 6.0.2 on 2026-03-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0002_add_fluxo_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('prazo_guarda_anos', models.PositiveIntegerField(verbose_name='Prazo de Guarda (anos)')),
                ('destinacao', models.CharField(choices=[('ELIMINACAO', 'Eliminacao'), ('GUARDA_PERMANENTE', 'Guarda Permanente'), ('TRANSFERENCIA', 'Transferencia para Arquivo Central')], max_length=20, verbose_name='Destinacao Final')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
            ],
            options={
                'verbose_name': 'Plano de Classificacao',
                'verbose_name_plural': 'Planos de Classificacao',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='guardadocumental',
            name='plano_classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardas', to='arquivo.planoclassificacao', verbose_name='Plano de Classificacao'),
        ),
    ]
