# Generated by Django 5.2.5 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0019_ofertacurso_template_sync_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SicaComponenteCurricular",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("periodo", models.PositiveSmallIntegerField(verbose_name="Periodo")),
                ("componente", models.CharField(max_length=200, verbose_name="Componente")),
                ("tipo", models.CharField(choices=[("OBRIGATORIO", "Obrigatorio"), ("OPTATIVO", "Optativo"), ("PRATICO", "Pratico")], default="OBRIGATORIO", max_length=20, verbose_name="Tipo do componente")),
                ("carga_horaria", models.PositiveIntegerField(verbose_name="Carga horaria")),
                ("ementa", models.TextField(blank=True, default="", verbose_name="Ementa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Componente Curricular SICA",
                "verbose_name_plural": "Componentes Curriculares SICA",
                "ordering": ["periodo", "componente", "id"],
            },
        ),
        migrations.CreateModel(
            name="SicaMatrizCurricular",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("versao", models.CharField(max_length=30, verbose_name="Versao")),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("VIGENTE", "Vigente"), ("ARQUIVADA", "Arquivada")], default="RASCUNHO", max_length=20, verbose_name="Status")),
                ("descricao", models.CharField(blank=True, default="", max_length=255, verbose_name="Descricao")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sica_matrizes", to="cursos.curso", verbose_name="Curso")),
            ],
            options={
                "verbose_name": "Matriz Curricular SICA",
                "verbose_name_plural": "Matrizes Curriculares SICA",
                "ordering": ["curso__nome", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SicaEquivalencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("componente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relacoes_equivalencia_origem", to="sica.sicacomponentecurricular")),
                ("equivalente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relacoes_equivalencia_destino", to="sica.sicacomponentecurricular")),
            ],
            options={
                "verbose_name": "Equivalencia SICA",
                "verbose_name_plural": "Equivalencias SICA",
            },
        ),
        migrations.CreateModel(
            name="SicaPreRequisito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("componente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relacoes_prerequisito", to="sica.sicacomponentecurricular")),
                ("prerequisito", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relacoes_dependencia", to="sica.sicacomponentecurricular")),
            ],
            options={
                "verbose_name": "Pre-requisito SICA",
                "verbose_name_plural": "Pre-requisitos SICA",
            },
        ),
        migrations.AddField(
            model_name="sicacomponentecurricular",
            name="equivalencias",
            field=models.ManyToManyField(blank=True, related_name="equivalente_de", through="sica.SicaEquivalencia", to="sica.sicacomponentecurricular"),
        ),
        migrations.AddField(
            model_name="sicacomponentecurricular",
            name="matriz",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="componentes", to="sica.sicamatrizcurricular", verbose_name="Matriz Curricular"),
        ),
        migrations.AddField(
            model_name="sicacomponentecurricular",
            name="prerequisitos",
            field=models.ManyToManyField(blank=True, related_name="e_prerequisito_de", through="sica.SicaPreRequisito", to="sica.sicacomponentecurricular"),
        ),
        migrations.AddConstraint(
            model_name="sicacomponentecurricular",
            constraint=models.UniqueConstraint(fields=("matriz", "periodo", "componente"), name="uniq_sica_componente_matriz_periodo_nome"),
        ),
        migrations.AddConstraint(
            model_name="sicamatrizcurricular",
            constraint=models.UniqueConstraint(fields=("curso", "versao"), name="uniq_sica_matriz_curso_versao"),
        ),
        migrations.AddConstraint(
            model_name="sicaequivalencia",
            constraint=models.UniqueConstraint(fields=("componente", "equivalente"), name="uniq_sica_equivalencia"),
        ),
        migrations.AddConstraint(
            model_name="sicaprerequisito",
            constraint=models.UniqueConstraint(fields=("componente", "prerequisito"), name="uniq_sica_prerequisito"),
        ),
    ]
