# Generated by Django 6.0.2 on 2026-03-02 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='unidades.unidade')),
            ],
        ),
    ]
