# Generated by Django 6.0.2 on 2026-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_calendarioletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='sigla',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
