# Generated by Django 6.0.3 on 2026-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_eixo_tecnologico_componentecurricular'),
        ('cursos', '0003_curso_sigla'),
    ]

    operations = [
    ]
