# Generated by Django 6.0.3 on 2026-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_merge_20260305_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Sigla'),
        ),
    ]
