# Generated by Django 6.0.2 on 2026-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_curso_moodle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(choices=[('tecnico', 'Educação Profissional Técnica'), ('formacao_inicial', 'Formação Inicial e Continuada'), ('itinerante', 'Qualificação Profissional Itinerante')], default='formacao_inicial', max_length=32, verbose_name='Tipo de Curso'),
        ),
    ]
