# Generated by Django 6.0.2 on 2026-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_ofertacurso_template_sync_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='conteudo_modulo',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo abordado no módulo'),
        ),
    ]
