# Generated by Django 6.0.2 on 2026-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='unidade',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
