# Generated by Django 6.0.2 on 2026-03-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_calendarioletivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=200, verbose_name='Nome do Candidato')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Validação'), ('VALIDADA', 'Validada'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('numero_inscricao', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Inscrição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('SORTEIO', 'Sorteio'), ('DEMANDA_ESPONTANEA', 'Demanda Espontânea'), ('PROVA', 'Prova'), ('ANALISE_CURRICULO', 'Análise de Currículo'), ('ENTREVISTA', 'Entrevista')], max_length=25, verbose_name='Modalidade')),
                ('data_realizacao', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='Data do Resultado')),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PREVISTO', max_length=15, verbose_name='Status')),
                ('criterios', models.TextField(blank=True, verbose_name='Critérios de Classificação')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado Publicado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_seletivos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processos Seletivos',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.PositiveIntegerField(verbose_name='Classificação')),
                ('pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pontuação')),
                ('situacao', models.CharField(choices=[('CONVOCADO', 'Convocado'), ('MATRICULADO', 'Matriculado'), ('DESISTENTE', 'Desistente'), ('ELIMINADO', 'Eliminado')], default='CONVOCADO', max_length=15, verbose_name='Situação')),
                ('data_convocacao', models.DateField(blank=True, null=True, verbose_name='Data da Convocação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='inscricoes.inscricao', verbose_name='Inscrição')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='inscricoes.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['classificacao'],
                'unique_together': {('processo', 'inscricao')},
            },
        ),
        migrations.CreateModel(
            name='PublicacaoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Edital')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Requisitos')),
                ('vagas', models.PositiveIntegerField(default=0, verbose_name='Nº de Vagas')),
                ('data_inicio', models.DateField(verbose_name='Início das Inscrições')),
                ('data_fim', models.DateField(verbose_name='Fim das Inscrições')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ENCERRADO', 'Encerrado')], default='RASCUNHO', max_length=15, verbose_name='Status')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_inscricao', to='cursos.curso', verbose_name='Curso')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_inscricao', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Publicação de Inscrição',
                'verbose_name_plural': 'Publicações de Inscrição',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='publicacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo_seletivo', to='inscricoes.publicacaoinscricao', verbose_name='Publicação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.publicacaoinscricao', verbose_name='Edital'),
        ),
        migrations.CreateModel(
            name='RecursoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo do Recurso')),
                ('data_recurso', models.DateField(auto_now_add=True, verbose_name='Data do Recurso')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta / Decisão')),
                ('data_decisao', models.DateField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='inscricoes.candidato', verbose_name='Candidato')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_decididos', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
            ],
            options={
                'verbose_name': 'Recurso de Inscrição',
                'verbose_name_plural': 'Recursos de Inscrição',
                'ordering': ['-data_recurso'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG / Documento de Identidade'), ('CPF', 'CPF'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('HISTORICO_ESCOLAR', 'Histórico Escolar'), ('FOTO', 'Foto 3x4'), ('OUTROS', 'Outros')], max_length=25, verbose_name='Tipo de Documento')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscricoes.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Documento da Inscrição',
                'verbose_name_plural': 'Documentos da Inscrição',
                'unique_together': {('inscricao', 'tipo')},
            },
        ),
    ]
