# Generated by Django 6.0.2 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoinscricao',
            options={'verbose_name': 'Documento da Inscricao', 'verbose_name_plural': 'Documentos da Inscricao'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Inscricao', 'verbose_name_plural': 'Inscricoes'},
        ),
        migrations.AlterModelOptions(
            name='publicacaoinscricao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Publicacao de Inscricao', 'verbose_name_plural': 'Publicacoes de Inscricao'},
        ),
        migrations.AlterModelOptions(
            name='recursoinscricao',
            options={'ordering': ['-data_recurso'], 'verbose_name': 'Recurso de Inscricao', 'verbose_name_plural': 'Recursos de Inscricao'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='cota_codigo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Codigo da Cota'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='modalidade_vaga',
            field=models.CharField(choices=[('AMPLA', 'Ampla Concorrencia'), ('COTAS', 'Cotas')], default='AMPLA', max_length=10, verbose_name='Modalidade de Vaga'),
        ),
        migrations.AddField(
            model_name='documentoinscricao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/documentos/%Y/%m', verbose_name='Arquivo Digital'),
        ),
        migrations.AddField(
            model_name='documentoinscricao',
            name='data_validacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validacao'),
        ),
        migrations.AddField(
            model_name='documentoinscricao',
            name='justificativa_validacao',
            field=models.TextField(blank=True, verbose_name='Justificativa da Validacao'),
        ),
        migrations.AddField(
            model_name='documentoinscricao',
            name='status_validacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDO', 'Valido'), ('INVALIDO', 'Invalido')], default='PENDENTE', max_length=10, verbose_name='Status de Validacao'),
        ),
        migrations.AddField(
            model_name='documentoinscricao',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_inscricao_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cota_codigo_opcao',
            field=models.CharField(blank=True, max_length=40, verbose_name='Codigo da Cota'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='modalidade_concorrencia',
            field=models.CharField(choices=[('AMPLA', 'Ampla Concorrencia'), ('COTAS', 'Cotas')], default='AMPLA', max_length=10, verbose_name='Modalidade de Concorrencia'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status_candidato',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('HOMOLOGADO', 'Homologado'), ('CLASSIFICADO', 'Classificado'), ('CONVOCADO', 'Convocado'), ('MATRICULADO', 'Matriculado'), ('LISTA_ESPERA', 'Lista de Espera'), ('INDEFERIDO', 'Indeferido'), ('DESISTENTE', 'Desistente')], default='INSCRITO', max_length=20, verbose_name='Status do Candidato'),
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='nota_corte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota de Corte'),
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='usa_cotas_lei_12711',
            field=models.BooleanField(default=True, verbose_name='Aplica Lei de Cotas'),
        ),
        migrations.AddField(
            model_name='publicacaoinscricao',
            name='codigo_edital',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Codigo do Edital'),
        ),
        migrations.AddField(
            model_name='publicacaoinscricao',
            name='modalidade_ingresso',
            field=models.CharField(choices=[('PROCESSO_SELETIVO', 'Processo Seletivo'), ('SORTEIO', 'Sorteio')], default='PROCESSO_SELETIVO', max_length=20, verbose_name='Modalidade de Ingresso'),
        ),
        migrations.AddField(
            model_name='publicacaoinscricao',
            name='nota_corte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota de Corte'),
        ),
        migrations.AddField(
            model_name='publicacaoinscricao',
            name='usa_cotas_lei_12711',
            field=models.BooleanField(default=True, verbose_name='Aplica Lei de Cotas'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='classificacao',
            field=models.PositiveIntegerField(verbose_name='Classificacao'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_convocacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Convocacao'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='inscricoes.inscricao', verbose_name='Inscricao'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pontuacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pontuacao'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='situacao',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('MATRICULADO', 'Matriculado'), ('LISTA_ESPERA', 'Lista de Espera'), ('RECLASSIFICADO', 'Reclassificado'), ('NAO_COMPARECEU', 'Nao Compareceu'), ('DESISTENTE', 'Desistente'), ('ELIMINADO', 'Eliminado')], default='CONVOCADO', max_length=15, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='documentoinscricao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscricoes.inscricao', verbose_name='Inscricao'),
        ),
        migrations.AlterField(
            model_name='documentoinscricao',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='documentoinscricao',
            name='tipo',
            field=models.CharField(choices=[('RG', 'RG / Documento de Identidade'), ('CPF', 'CPF'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residencia'), ('HISTORICO_ESCOLAR', 'Historico Escolar'), ('FOTO', 'Foto 3x4'), ('OUTROS', 'Outros')], max_length=25, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscricao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='numero_inscricao',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numero de Inscricao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Validacao'), ('VALIDADA', 'Validada'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario do Sistema'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='criterios',
            field=models.TextField(blank=True, verbose_name='Criterios de Classificacao'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='data_realizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Realizacao'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='modalidade',
            field=models.CharField(choices=[('SORTEIO', 'Sorteio'), ('DEMANDA_ESPONTANEA', 'Demanda Espontanea'), ('PROVA', 'Prova'), ('ANALISE_CURRICULO', 'Analise de Curriculo'), ('ENTREVISTA', 'Entrevista')], max_length=25, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='publicacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo_seletivo', to='inscricoes.publicacaoinscricao', verbose_name='Publicacao'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_seletivos', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='status',
            field=models.CharField(choices=[('PREVISTO', 'Previsto'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido')], default='PREVISTO', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='publicacaoinscricao',
            name='data_fim',
            field=models.DateField(verbose_name='Fim das Inscricoes'),
        ),
        migrations.AlterField(
            model_name='publicacaoinscricao',
            name='data_inicio',
            field=models.DateField(verbose_name='Inicio das Inscricoes'),
        ),
        migrations.AlterField(
            model_name='publicacaoinscricao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao / Requisitos'),
        ),
        migrations.AlterField(
            model_name='publicacaoinscricao',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Titulo do Edital'),
        ),
        migrations.AlterField(
            model_name='publicacaoinscricao',
            name='vagas',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero de Vagas'),
        ),
        migrations.AlterField(
            model_name='recursoinscricao',
            name='data_decisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Decisao'),
        ),
        migrations.AlterField(
            model_name='recursoinscricao',
            name='resposta',
            field=models.TextField(blank=True, verbose_name='Resposta / Decisao'),
        ),
        migrations.CreateModel(
            name='ChamadaProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero da Chamada')),
                ('tipo', models.CharField(choices=[('REGULAR', 'Regular'), ('RECLASSIFICACAO', 'Reclassificacao')], default='REGULAR', max_length=20, verbose_name='Tipo')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicacao')),
                ('prazo_matricula_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio do Prazo de Matricula')),
                ('prazo_matricula_fim', models.DateField(blank=True, null=True, verbose_name='Fim do Prazo de Matricula')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada'), ('ENCERRADA', 'Encerrada')], default='RASCUNHO', max_length=12, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='inscricoes.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Chamada do Processo Seletivo',
                'verbose_name_plural': 'Chamadas do Processo Seletivo',
                'ordering': ['processo_id', 'numero', 'id'],
                'unique_together': {('processo', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='chamada_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_atuais', to='inscricoes.chamadaprocessoseletivo', verbose_name='Chamada Atual'),
        ),
        migrations.CreateModel(
            name='ConvocacaoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_vaga', models.CharField(default='AMPLA', max_length=10, verbose_name='Modalidade da Vaga')),
                ('cota_codigo', models.CharField(blank=True, max_length=40, verbose_name='Codigo da Cota')),
                ('classificacao_na_chamada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Classificacao na Chamada')),
                ('status', models.CharField(choices=[('CONVOCADO', 'Convocado'), ('MATRICULADO', 'Matriculado'), ('INDEFERIDO', 'Indeferido'), ('NAO_COMPARECEU', 'Nao Compareceu'), ('DESISTENTE', 'Desistente'), ('RECLASSIFICADO', 'Reclassificado')], default='CONVOCADO', max_length=15, verbose_name='Status')),
                ('data_status', models.DateField(blank=True, null=True, verbose_name='Data do Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='inscricoes.candidato', verbose_name='Candidato')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='inscricoes.chamadaprocessoseletivo', verbose_name='Chamada')),
            ],
            options={
                'verbose_name': 'Convocacao de Candidato',
                'verbose_name_plural': 'Convocacoes de Candidatos',
                'ordering': ['chamada_id', 'classificacao_na_chamada', 'id'],
                'unique_together': {('chamada', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='CotaProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, verbose_name='Codigo da Cota')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Cota')),
                ('percentual_vagas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Vagas')),
                ('vagas_reservadas', models.PositiveIntegerField(default=0, verbose_name='Vagas Reservadas')),
                ('ordem_remanejamento', models.PositiveIntegerField(default=0, verbose_name='Ordem de Remanejamento')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas', to='inscricoes.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Cota do Processo Seletivo',
                'verbose_name_plural': 'Cotas do Processo Seletivo',
                'ordering': ['processo_id', 'ordem_remanejamento', 'id'],
                'unique_together': {('processo', 'codigo')},
            },
        ),
    ]
