# Generated by Django 6.0.2 on 2026-03-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0003_matricula_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='matriculas.matricula')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('matricula', 'data')},
            },
        ),
    ]
